/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KnowledgeSystemPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  baseUrl: "https://api.deepseek.com/anthropic",
  model: "",
  models: [],
  sourceFolder: "/",
  outputFolder: "/",
  timeAttr: "",
  timeFormat: "YYYY-MM-DD",
  recentDays: 7,
  reviewAttr: "approved",
  reviewDefault: "\u672A\u5BA1",
  categoryAttr: "category",
  categoryDefault: "\u672A\u5206\u7C7B",
  timestampProperty: "created",
  sourceAttr: "source",
  earliestTime: "",
  customApiKey: "",
  customModel: "",
  extraProperties: []
};

// src/settingsTab.ts
var import_obsidian3 = require("obsidian");

// src/folderSuggest.ts
var import_obsidian = require("obsidian");
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const folders = [];
    const lower = (query || "").toLowerCase();
    const visit = (f) => {
      folders.push(f);
      f.children.forEach((c) => {
        if (c instanceof import_obsidian.TFolder) visit(c);
      });
    };
    this.app.vault.getAllLoadedFiles().forEach((f) => {
      if (f instanceof import_obsidian.TFolder) visit(f);
    });
    return folders.filter((f) => f.path.toLowerCase().includes(lower)).slice(0, 50);
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path || "/");
  }
  selectSuggestion(folder) {
    this.inputEl.value = folder.path || "/";
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/core.ts
var import_obsidian2 = require("obsidian");

// src/utils/sse.ts
function tryParsed(raw) {
  if (raw === "") return "";
  try {
    return JSON.parse(raw);
  } catch (e) {
    return raw;
  }
}
function parseAnthropicSSE(lines) {
  const out = [];
  let event = "";
  let dataLines = [];
  const flush = () => {
    if (event || dataLines.length > 0) {
      out.push({ event: event || "", data: tryParsed(dataLines.join("\n")) });
    }
    event = "";
    dataLines = [];
  };
  for (const rawLine of lines) {
    const line = !!rawLine && rawLine.endsWith("\r") ? rawLine.slice(0, -1) : rawLine;
    if (line === "") {
      flush();
      continue;
    }
    if (line.startsWith(":")) continue;
    if (line.startsWith("event:")) {
      event = line.slice(6).trim();
      continue;
    }
    if (line.startsWith("data:")) {
      dataLines.push(line.slice(5).trimStart());
      continue;
    }
  }
  flush();
  return out;
}
function parseAnthropicResponse(json) {
  var _a;
  const obj = json && typeof json === "object" ? json : {};
  const content = Array.isArray(obj.content) ? obj.content : [];
  const blocks = content.map((c) => {
    var _a2, _b, _c, _d, _e, _f;
    if ((c == null ? void 0 : c.type) === "thinking") {
      return { type: "thinking", thinking: (_a2 = c.thinking) != null ? _a2 : "", text: "", signature: (_b = c.signature) != null ? _b : "", id: "", name: "", input: {}, partialJson: "" };
    }
    if ((c == null ? void 0 : c.type) === "tool_use") {
      return { type: "tool_use", thinking: "", text: "", signature: "", id: (_c = c.id) != null ? _c : "", name: (_d = c.name) != null ? _d : "", input: (_e = c.input) != null ? _e : {}, partialJson: "" };
    }
    return { type: "text", thinking: "", text: (_f = c == null ? void 0 : c.text) != null ? _f : "", signature: "", id: "", name: "", input: {}, partialJson: "" };
  });
  return { blocks, stop_reason: (_a = obj.stop_reason) != null ? _a : null };
}

// src/utils/endpoints.ts
function normalizeBase(base) {
  return (base || "").trim().replace(/\/+$/, "");
}
function hasAnthropicPath(base) {
  return /\/anthropic(\/|$)/i.test(normalizeBase(base));
}
function stripAnthropic(base) {
  return normalizeBase(base).replace(/\/anthropic\/?/i, "").replace(/\/+$/, "");
}
function hasV1Segment(base) {
  return /(^|\/)v1(\/|$)/i.test(normalizeBase(base));
}
function chatEndpointCandidates(baseUrl) {
  const base = normalizeBase(baseUrl);
  if (!base) return [];
  if (hasAnthropicPath(base)) return [`${base}/v1/messages`];
  if (hasV1Segment(base)) return [`${base}/messages`];
  return [`${base}/v1/messages`, `${base}/anthropic/v1/messages`];
}
function modelsEndpointCandidates(baseUrl) {
  const base = normalizeBase(baseUrl);
  if (!base) return [];
  if (hasAnthropicPath(base)) {
    const root = stripAnthropic(base);
    return [`${root}/models`, `${root}/v1/models`];
  }
  if (hasV1Segment(base)) return [`${base}/models`];
  return [`${base}/models`, `${base}/v1/models`];
}

// src/utils/index.ts
var DAY_MS = 864e5;
function parseTimestamp(value, moment, formats) {
  if (typeof value === "number") return value > 1e12 ? value : value * 1e3;
  if (value instanceof Date) return value.getTime();
  if (typeof value !== "string") return null;
  const s = value.trim();
  if (!s) return null;
  for (const f of formats) {
    if (!f) continue;
    const m = moment(s, f, true);
    if (m && typeof m.isValid === "function" && m.isValid()) return m.valueOf();
  }
  return null;
}
function resolveTimestamp(frontmatter, ctimeMs, moment, timeAttr, formats) {
  if (timeAttr) {
    const v = frontmatter[timeAttr];
    if (v !== void 0 && v !== null) {
      const ts = parseTimestamp(v, moment, formats);
      if (ts !== null) return ts;
    }
  }
  return ctimeMs;
}
function countRecent(items, opts) {
  const { moment, timeAttr, formats, nowMs, days } = opts;
  const cutoff = nowMs - Math.max(1, Math.floor(days || 1)) * DAY_MS;
  let n = 0;
  for (const item of items) {
    if (!item.isMd) continue;
    const ts = resolveTimestamp(item.frontmatter, item.ctimeMs, moment, timeAttr, formats);
    if (ts >= cutoff) n++;
  }
  return n;
}
function extractLastChars(text, n) {
  return [...text].slice(-n).join("");
}
function buildFrontmatter(vals, cfg) {
  const lines = [
    `${cfg.timestampProperty}: ${cfg.moment(vals.timestampMs).format(cfg.timeFormat)}`,
    `${cfg.sourceAttr}: ${vals.source}`
  ];
  const extra = cfg.extraProperties && cfg.extraProperties.length > 0 ? cfg.extraProperties : null;
  if (extra) {
    for (const { key, value } of extra) lines.push(`${key}: ${value}`);
  } else {
    if (cfg.reviewAttr && cfg.reviewDefault != null) lines.push(`${cfg.reviewAttr}: ${cfg.reviewDefault}`);
    if (cfg.categoryAttr && cfg.categoryDefault != null) lines.push(`${cfg.categoryAttr}: ${cfg.categoryDefault}`);
  }
  return lines.join("\n");
}
function migrateExtraProperties(input) {
  const extra = input.extraProperties;
  if (Array.isArray(extra) && extra.length > 0) {
    return extra.map((e) => {
      var _a, _b;
      const item = e;
      return { key: String((_a = item == null ? void 0 : item.key) != null ? _a : ""), value: String((_b = item == null ? void 0 : item.value) != null ? _b : "") };
    });
  }
  const out = [];
  const reviewAttr = input.reviewAttr;
  const reviewDefault = input.reviewDefault;
  if (reviewAttr && reviewDefault != null) out.push({ key: String(reviewAttr), value: String(reviewDefault) });
  const categoryAttr = input.categoryAttr;
  const categoryDefault = input.categoryDefault;
  if (categoryAttr && categoryDefault != null) out.push({ key: String(categoryAttr), value: String(categoryDefault) });
  return out;
}
function stripFrontmatter(content) {
  if (content.startsWith("---")) {
    const idx = content.indexOf("\n---", 3);
    if (idx >= 0) {
      let rest = content.slice(idx + 4);
      if (rest.startsWith("\n")) rest = rest.slice(1);
      return rest;
    }
  }
  return content;
}

// src/core.ts
var FALLBACK_FORMATS = ["YYYY-MM-DD", "YYYY.MM.DD", "YYYY/MM/DD"];
function formatsFor(plugin) {
  const f = (plugin.settings.timeFormat || "").trim();
  return [f, ...FALLBACK_FORMATS].filter((x, i, arr) => !!x && arr.indexOf(x) === i);
}
function frontmatterOf(app, file) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  return (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
}
function resolveSourceFolder(plugin) {
  const raw = (plugin.settings.sourceFolder || "/").trim();
  if (raw === "/" || raw === "") return vaultRoot(plugin.app);
  const p = raw.replace(/^\/+|\/+$/g, "");
  const found = plugin.app.vault.getAbstractFileByPath(p);
  return found instanceof import_obsidian2.TFolder ? found : vaultRoot(plugin.app);
}
function vaultRoot(app) {
  var _a;
  const vault = app.vault;
  if (typeof vault.getRoot === "function") {
    const r = vault.getRoot();
    if (r instanceof import_obsidian2.TFolder) return r;
  }
  const byEmpty = app.vault.getAbstractFileByPath("");
  return byEmpty instanceof import_obsidian2.TFolder ? byEmpty : (_a = vault.getRoot) == null ? void 0 : _a.call(vault);
}
function getMarkdownFilesInFolder(folder) {
  const result = [];
  const visit = (f) => {
    for (const child of f.children) {
      if (child instanceof import_obsidian2.TFile && child.extension === "md") {
        result.push(child);
      } else if (child instanceof import_obsidian2.TFolder) {
        visit(child);
      }
    }
  };
  visit(folder);
  return result;
}
function countRecentFiles(plugin) {
  const folder = resolveSourceFolder(plugin);
  const files = getMarkdownFilesInFolder(folder);
  const items = files.map((file) => ({
    isMd: true,
    frontmatter: frontmatterOf(plugin.app, file),
    ctimeMs: file.stat.ctime
  }));
  const count = countRecent(items, {
    moment: window.moment,
    timeAttr: plugin.settings.timeAttr || "",
    formats: formatsFor(plugin),
    nowMs: Date.now(),
    days: plugin.settings.recentDays
  });
  new import_obsidian2.Notice(`\u6E90\u6587\u4EF6\u5939\u6700\u8FD1 ${plugin.settings.recentDays} \u5929\u5171\u6709 ${count} \u4E2A\u6587\u4EF6`);
  return count;
}
function joinOutputPath(folder, name) {
  const raw = (folder || "/").trim();
  const base = raw === "/" || raw === "" ? "" : raw.replace(/^\/+|\/+$/g, "");
  const joined = base ? `${base}/${name}` : name;
  return joined.replace(/\/+/g, "/").replace(/^\/+/, "");
}
async function ensureFolderExists(app, folder) {
  const raw = (folder || "/").trim();
  const parts = (raw === "/" || raw === "" ? "" : raw.replace(/^\/+|\/+$/g, "")).split("/").filter(Boolean);
  let cur = "";
  for (const part of parts) {
    cur = cur ? `${cur}/${part}` : part;
    if (!app.vault.getAbstractFileByPath(cur)) {
      await app.vault.createFolder(cur);
    }
  }
}
async function outputLatestContent(plugin) {
  const folder = resolveSourceFolder(plugin);
  const files = getMarkdownFilesInFolder(folder);
  if (files.length === 0) {
    new import_obsidian2.Notice("\u6E90\u6587\u4EF6\u5939\u4E2D\u6CA1\u6709\u53EF\u7528\u7684 Markdown \u6587\u4EF6");
    return "";
  }
  const formats = formatsFor(plugin);
  const timeAttr = plugin.settings.timeAttr || "";
  const tsOf = (file) => resolveTimestamp(frontmatterOf(plugin.app, file), file.stat.ctime, window.moment, timeAttr, formats);
  let latest = files[0];
  let latestTs = tsOf(latest);
  for (const file of files) {
    const ts = tsOf(file);
    if (ts > latestTs) {
      latestTs = ts;
      latest = file;
    }
  }
  const raw = await plugin.app.vault.read(latest);
  const body = stripFrontmatter(raw);
  const last100 = extractLastChars(body, 100);
  const now = window.moment();
  const frontmatter = buildFrontmatter(
    { source: latest.path, timestampMs: now.valueOf() },
    {
      timestampProperty: plugin.settings.timestampProperty,
      sourceAttr: plugin.settings.sourceAttr || "source",
      moment: window.moment,
      timeFormat: plugin.settings.timeFormat,
      extraProperties: plugin.settings.extraProperties,
      reviewAttr: plugin.settings.reviewAttr,
      reviewDefault: plugin.settings.reviewDefault,
      categoryAttr: plugin.settings.categoryAttr,
      categoryDefault: plugin.settings.categoryDefault
    }
  );
  const fileName = `${latest.basename}-\u6700\u65B0\u5185\u5BB9-${now.valueOf()}.md`;
  const outPath = joinOutputPath(plugin.settings.outputFolder, fileName);
  await ensureFolderExists(plugin.app, plugin.settings.outputFolder);
  await plugin.app.vault.create(outPath, `---
${frontmatter}
---
${last100}`);
  new import_obsidian2.Notice(`\u5DF2\u8F93\u51FA\uFF1A${outPath}`);
  return outPath;
}
function mapHttpError(status) {
  if (status === 401 || status === 403) return "API Key \u65E0\u6548";
  if (status === 402) return "\u4F59\u989D\u4E0D\u8DB3";
  if (status === 429) return "\u9650\u6D41";
  return "\u8BF7\u6C42\u5931\u8D25";
}
async function listFromResponse(res) {
  const body = typeof (res == null ? void 0 : res.json) === "function" ? await res.json() : res == null ? void 0 : res.json;
  if (!((res == null ? void 0 : res.status) >= 200 && (res == null ? void 0 : res.status) < 300)) return null;
  const data = body == null ? void 0 : body.data;
  return Array.isArray(data) ? data.map((m) => m && typeof m.id === "string" ? m.id : "").filter((x) => x.length > 0) : [];
}
async function fetchModelList(apiKey, baseUrl) {
  var _a;
  const key = (apiKey || "").trim();
  if (!key) {
    const message = "\u8BF7\u5148\u586B\u5199 API Key";
    new import_obsidian2.Notice(message);
    return { ok: false, modelIds: [], message };
  }
  const base = (baseUrl || "https://api.deepseek.com").trim().replace(/\/+$/, "");
  try {
    let lastStatus = 0;
    for (const url of modelsEndpointCandidates(base)) {
      const res = await (0, import_obsidian2.requestUrl)({
        url,
        method: "GET",
        headers: { Authorization: `Bearer ${key}` },
        throw: false
      });
      const ids = await listFromResponse(res);
      if (ids && ids.length > 0) {
        const message2 = `\u6210\u529F\u83B7\u53D6 ${ids.length} \u4E2A\u6A21\u578B\uFF1A${ids[0]}\uFF08${url}\uFF09`;
        new import_obsidian2.Notice(message2);
        return { ok: true, modelIds: ids, message: message2 };
      }
      lastStatus = res.status;
    }
    const message = `${mapHttpError(lastStatus)}\uFF08HTTP ${lastStatus}\uFF09`;
    new import_obsidian2.Notice(message);
    return { ok: false, modelIds: [], message };
  } catch (e) {
    const message = "\u7F51\u7EDC\u9519\u8BEF\uFF1A" + ((_a = e == null ? void 0 : e.message) != null ? _a : "\u672A\u77E5\u9519\u8BEF");
    new import_obsidian2.Notice(message);
    return { ok: false, modelIds: [], message };
  }
}
function maybeAutoCorrect(base, url, cb) {
  if (!cb) return;
  if (hasAnthropicPath(base)) return;
  if (!/\/anthropic\/v1\/messages$/i.test(url)) return;
  cb(url);
}
async function fetchAnthropicMessages(settings, messages, opts) {
  var _a;
  const base = (settings.baseUrl || "https://api.deepseek.com/anthropic").trim().replace(/\/+$/, "");
  const body = {
    model: settings.model,
    max_tokens: 4096,
    ...(opts == null ? void 0 : opts.system) ? { system: opts.system } : {},
    messages,
    ...(opts == null ? void 0 : opts.tools) && opts.tools.length > 0 ? { tools: opts.tools } : {},
    stream: false
  };
  const candidates = chatEndpointCandidates(base);
  let lastStatus = 0;
  let lastUrl = "";
  let requestError;
  for (let i = 0; i < candidates.length; i++) {
    const url = candidates[i];
    lastUrl = url;
    try {
      const res = await (0, import_obsidian2.requestUrl)({
        url,
        method: "POST",
        headers: {
          "content-type": "application/json",
          "x-api-key": settings.apiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify(body),
        throw: false
      });
      const status = res.status;
      if (status >= 200 && status < 300) {
        maybeAutoCorrect(base, url, opts == null ? void 0 : opts.onAutoCorrect);
        return { status, text: await extractResponseText(res), url };
      }
      lastStatus = status;
      if (status === 404 && i < candidates.length - 1) continue;
      return { status, text: (await extractResponseText(res)).slice(0, 300), url };
    } catch (e) {
      requestError = (_a = e == null ? void 0 : e.message) != null ? _a : "\u7F51\u7EDC\u9519\u8BEF";
      if (i < candidates.length - 1) continue;
      return { status: 0, text: "", requestError, url: lastUrl };
    }
  }
  return { status: lastStatus, text: "", url: lastUrl, requestError };
}
async function streamAnthropicMessages(settings, messages, opts) {
  var _a;
  const base = (settings.baseUrl || "https://api.deepseek.com/anthropic").trim().replace(/\/+$/, "");
  const body = {
    model: settings.model,
    max_tokens: 4096,
    ...opts.system ? { system: opts.system } : {},
    messages,
    ...opts.tools && opts.tools.length > 0 ? { tools: opts.tools } : {},
    stream: true
  };
  const candidates = chatEndpointCandidates(base);
  let lastUrl = "";
  let lastStatus = 0;
  try {
    for (let i = 0; i < candidates.length; i++) {
      const url = lastUrl = candidates[i];
      const res = await window.fetch(url, {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "x-api-key": settings.apiKey,
          "anthropic-version": "2023-06-01",
          "anthropic-dangerous-direct-browser-access": "true"
        },
        body: JSON.stringify(body),
        signal: opts.signal
      });
      if (res.ok && res.body) {
        const reader = res.body.getReader();
        const decoder = new TextDecoder();
        let text = "";
        for (; ; ) {
          const { done, value } = await reader.read();
          if (done) break;
          text += decoder.decode(value, { stream: true });
        }
        const events = parseAnthropicSSE(text.split("\n"));
        for (const event of events) opts.onEvent(event);
        maybeAutoCorrect(base, url, opts.onAutoCorrect);
        return { ok: true, url };
      }
      lastStatus = res.status;
      if (res.status === 404 && i < candidates.length - 1) continue;
      return { ok: false, status: res.status, error: `HTTP ${res.status} POST ${url}`, url };
    }
  } catch (e) {
    return { ok: false, error: (_a = e == null ? void 0 : e.message) != null ? _a : "\u7F51\u7EDC\u9519\u8BEF", url: lastUrl };
  }
  return { ok: false, status: lastStatus, error: `HTTP ${lastStatus} POST ${lastUrl}`, url: lastUrl };
}
async function extractResponseText(res) {
  if (typeof (res == null ? void 0 : res.text) === "string" && res.text) return res.text;
  const j = res == null ? void 0 : res.json;
  if (typeof j === "string") return j;
  if (typeof j === "function") {
    const v = await j();
    return typeof v === "string" ? v : JSON.stringify(v != null ? v : "");
  }
  return String(j != null ? j : "");
}

// src/settingsTab.ts
function renderSettings(app, plugin, containerEl) {
  new SettingsRenderer(app, plugin).render(containerEl);
}
var SettingsRenderer = class {
  constructor(app, plugin) {
    this.activeTab = "connection";
    this.modelDropdown = null;
    this.groupEls = [];
    this.groupCollapsed = /* @__PURE__ */ new Map();
    this.app = app;
    this.plugin = plugin;
    this.currentModels = Array.isArray(plugin.settings.models) ? plugin.settings.models.slice() : [];
  }
  render(containerEl) {
    this.containerEl = containerEl;
    containerEl.empty();
    this.modelDropdown = null;
    this.groupEls = [];
    this.groupCollapsed.clear();
    this.renderTabs(containerEl);
    this.renderSearch(containerEl);
    this.renderActiveTab(containerEl.createDiv({ cls: "ks-tab-content" }));
  }
  // -------------------------------------------------------------------------
  // tab bar / search / active tab
  // -------------------------------------------------------------------------
  renderTabs(containerEl) {
    const tabs = [
      { id: "connection", label: "\u8FDE\u63A5" },
      { id: "folder", label: "\u6587\u4EF6\u5939" },
      { id: "time", label: "\u65F6\u95F4" },
      { id: "output", label: "\u8F93\u51FA\u5C5E\u6027" },
      { id: "test", label: "\u6D4B\u8BD5\u5DE5\u5177" }
    ];
    const tabsEl = containerEl.createDiv({ cls: "ks-tabs" });
    for (const tab of tabs) {
      const tabEl = tabsEl.createDiv({ cls: "ks-tab" });
      tabEl.setText(tab.label);
      tabEl.dataset.tabId = tab.id;
      if (this.activeTab === tab.id) tabEl.addClass("is-active");
      tabEl.addEventListener("click", () => {
        this.activeTab = tab.id;
        this.render(this.containerEl);
      });
    }
  }
  renderActiveTab(containerEl) {
    switch (this.activeTab) {
      case "connection":
        this.renderConnectionGroup(containerEl);
        this.renderCustomProviderGroup(containerEl);
        break;
      case "folder":
        this.renderFolderGroup(containerEl);
        break;
      case "time":
        this.renderTimeGroup(containerEl);
        break;
      case "output":
        this.renderOutputGroup(containerEl);
        break;
      case "test":
        this.renderTestGroup(containerEl);
        break;
    }
  }
  renderSearch(containerEl) {
    const wrap = containerEl.createDiv({ cls: "ks-search" });
    const iconEl = wrap.createSpan({ cls: "ks-search-icon" });
    (0, import_obsidian3.setIcon)(iconEl, "search");
    const input = wrap.createEl("input", { cls: "ks-search-input" });
    input.type = "text";
    input.placeholder = "\u641C\u7D22\u8BBE\u7F6E...";
    input.addEventListener("input", () => this.filterSettings(input.value));
  }
  createGroup(containerEl, title, collapsed) {
    const groupEl = containerEl.createDiv({ cls: "ks-group" });
    const headingEl = groupEl.createDiv({ cls: "ks-group-heading" });
    const iconEl = headingEl.createSpan({ cls: "ks-group-icon" });
    (0, import_obsidian3.setIcon)(iconEl, collapsed ? "chevron-right" : "chevron-down");
    headingEl.createSpan({ cls: "ks-group-title", text: title });
    const bodyEl = groupEl.createDiv({ cls: "ks-group-body" });
    if (collapsed) groupEl.addClass("ks-collapsed");
    this.groupCollapsed.set(groupEl, collapsed);
    this.groupEls.push(groupEl);
    headingEl.addEventListener("click", () => {
      const isCollapsed = groupEl.hasClass("ks-collapsed");
      groupEl.toggleClass("ks-collapsed", !isCollapsed);
      this.groupCollapsed.set(groupEl, !isCollapsed);
      (0, import_obsidian3.setIcon)(iconEl, isCollapsed ? "chevron-down" : "chevron-right");
    });
    return bodyEl;
  }
  markSearchable(setting, text) {
    setting.settingEl.setAttribute("data-search", text);
  }
  updateSetting(key, value) {
    this.plugin.settings[key] = value;
    void this.plugin.saveSettings();
  }
  filterSettings(query) {
    const q = (query || "").trim().toLowerCase();
    const content = this.containerEl.querySelector(".ks-tab-content");
    if (!content) return;
    content.querySelectorAll(".setting-item").forEach((el) => {
      const elm = el;
      const hay = ((elm.getAttribute("data-search") || "") + " " + (elm.textContent || "")).toLowerCase();
      elm.style.display = q && hay.includes(q) ? "" : q ? "none" : "";
    });
    for (const groupEl of this.groupEls) {
      if (q) {
        groupEl.removeClass("ks-collapsed");
      } else if (this.groupCollapsed.get(groupEl)) {
        groupEl.addClass("ks-collapsed");
      } else {
        groupEl.removeClass("ks-collapsed");
      }
    }
  }
  // -------------------------------------------------------------------------
  // connection
  // -------------------------------------------------------------------------
  renderConnectionGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u8FDE\u63A5", false);
    const apiKey = new import_obsidian3.Setting(bodyEl).setName("API Key").setDesc("Anthropic \u517C\u5BB9\u670D\u52A1\u7684 API Key\uFF08x-api-key\uFF09\uFF0C\u7528\u4E8E\u804A\u5929\u4E0E\u83B7\u53D6\u6A21\u578B\u5217\u8868\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u7C98\u8D34\u4F60\u7684 API Key").setValue(this.plugin.settings.apiKey).onChange((value) => this.updateSetting("apiKey", value));
    });
    this.markSearchable(apiKey, "\u8FDE\u63A5 anthropic API Key \u5BC6\u94A5");
    const test = new import_obsidian3.Setting(bodyEl).setName("\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B").setDesc("\u8C03\u7528\u670D\u52A1\u5546\u6A21\u578B\u5217\u8868\u63A5\u53E3\uFF08\u5148\u8BD5 /models\uFF0C\u56DE\u9000 /v1/models\uFF09\uFF0C\u586B\u5145\u4E0B\u65B9\u6A21\u578B\u4E0B\u62C9\u6846\u3002").addButton(
      (btn) => btn.setButtonText("\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B").setCta().onClick(async () => {
        await this.refreshModels();
      })
    );
    this.markSearchable(test, "\u8FDE\u63A5 \u6D4B\u8BD5 \u83B7\u53D6 \u6A21\u578B \u5237\u65B0");
    const model = new import_obsidian3.Setting(bodyEl).setName("\u9ED8\u8BA4\u6A21\u578B").setDesc("\u53EF\u7528\u7684\u6A21\u578B\u5217\u8868\uFF08\u6765\u81EA\u670D\u52A1\u5546\u6A21\u578B\u63A5\u53E3\uFF0C\u4E0D\u786C\u7F16\u7801\uFF09\u3002").addDropdown((drop) => {
      this.modelDropdown = drop;
      this.populateModelDropdown(drop);
      drop.onChange((value) => this.updateSetting("model", value));
    });
    this.markSearchable(model, "\u8FDE\u63A5 \u9ED8\u8BA4\u6A21\u578B \u4E0B\u62C9 \u6A21\u578B");
  }
  renderCustomProviderGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546", true);
    const baseUrl = new import_obsidian3.Setting(bodyEl).setName("Base URL").setDesc("Anthropic \u517C\u5BB9\u670D\u52A1\u7684\u57FA\u7840\u5730\u5740\u3002\u586B https://api.deepseek.com \u6216 https://api.deepseek.com/anthropic \u5747\u53EF\uFF1A\u804A\u5929\u4F1A\u81EA\u52A8\u63A2\u6D4B /anthropic \u7AEF\u70B9\uFF0C\u6A21\u578B\u5217\u8868\u81EA\u52A8\u63A2\u6D4B\u6839\u7AEF\u70B9\u3002\u9ED8\u8BA4 DeepSeek Anthropic \u7AEF\u70B9\u3002").addText(
      (text) => text.setPlaceholder("https://api.deepseek.com/anthropic").setValue(this.plugin.settings.baseUrl).onChange((value) => this.updateSetting("baseUrl", value))
    );
    this.markSearchable(baseUrl, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 base_url \u5730\u5740 base url anthropic");
    const customApiKey = new import_obsidian3.Setting(bodyEl).setName("API Key").setDesc("\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684 API Key\uFF08\u9884\u7559\uFF09\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u7C98\u8D34\u4F60\u7684 API Key").setValue(this.plugin.settings.customApiKey).onChange((value) => this.updateSetting("customApiKey", value));
    });
    this.markSearchable(customApiKey, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 api_key \u5BC6\u94A5");
    const customModel = new import_obsidian3.Setting(bodyEl).setName("\u6A21\u578B").setDesc("\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684\u6A21\u578B ID\uFF08\u9884\u7559\uFF09\u3002").addText(
      (text) => text.setPlaceholder("model-id").setValue(this.plugin.settings.customModel).onChange((value) => this.updateSetting("customModel", value))
    );
    this.markSearchable(customModel, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 model \u6A21\u578B");
  }
  // -------------------------------------------------------------------------
  // folder
  // -------------------------------------------------------------------------
  renderFolderGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u6587\u4EF6\u5939", false);
    const source = new import_obsidian3.Setting(bodyEl).setName("\u6E90\u6587\u4EF6\u5939").setDesc("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570\u65F6\u626B\u63CF\u7684\u6587\u4EF6\u5939\u3002").addText((text) => {
      text.setPlaceholder("/").setValue(this.plugin.settings.sourceFolder).onChange((value) => this.updateSetting("sourceFolder", value));
      new FolderSuggest(this.app, text.inputEl);
    });
    this.markSearchable(source, "\u6587\u4EF6\u5939 \u6E90\u6587\u4EF6\u5939 \u8F93\u5165 \u76EE\u5F55");
    const output = new import_obsidian3.Setting(bodyEl).setName("\u8F93\u51FA\u6587\u4EF6\u5939").setDesc("\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5\u751F\u6210\u6587\u4EF6\u7684\u6587\u4EF6\u5939\u3002").addText((text) => {
      text.setPlaceholder("/").setValue(this.plugin.settings.outputFolder).onChange((value) => this.updateSetting("outputFolder", value));
      new FolderSuggest(this.app, text.inputEl);
    });
    this.markSearchable(output, "\u6587\u4EF6\u5939 \u8F93\u51FA\u6587\u4EF6\u5939 \u8F93\u5165 \u76EE\u5F55");
  }
  // -------------------------------------------------------------------------
  // time
  // -------------------------------------------------------------------------
  renderTimeGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u65F6\u95F4", false);
    const timeProp = new import_obsidian3.Setting(bodyEl).setName("\u65F6\u95F4\u5C5E\u6027\u540D").setDesc("\u8BFB\u53D6\u6587\u4EF6\u65F6\u95F4\u4F7F\u7528\u7684 frontmatter \u5C5E\u6027\u540D\uFF1B\u7559\u7A7A\u5219\u4F7F\u7528\u6587\u4EF6\u521B\u5EFA\u65F6\u95F4\u3002").addText(
      (text) => text.setPlaceholder("\u5982\uFF1Adate").setValue(this.plugin.settings.timeAttr).onChange((value) => this.updateSetting("timeAttr", value))
    );
    this.markSearchable(timeProp, "\u65F6\u95F4 \u65F6\u95F4\u5C5E\u6027\u540D \u5C5E\u6027 \u5B57\u6BB5");
    const timeFormat = new import_obsidian3.Setting(bodyEl).setName("\u65F6\u95F4\u6233\u683C\u5F0F").setDesc("moment \u517C\u5BB9\u7684\u65F6\u95F4\u683C\u5F0F\uFF0C\u4F8B\u5982 YYYY-MM-DD\u3002").addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.timeFormat).onChange((value) => this.updateSetting("timeFormat", value))
    );
    this.markSearchable(timeFormat, "\u65F6\u95F4 \u65F6\u95F4\u6233\u683C\u5F0F \u65F6\u95F4\u683C\u5F0F");
    const recentDays = new import_obsidian3.Setting(bodyEl).setName("\u6700\u8FD1 N \u5929").setDesc("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570\u65F6\u56DE\u770B\u7684\u5929\u6570\u3002").addText((text) => {
      text.inputEl.type = "number";
      text.setPlaceholder("7").setValue(String(this.plugin.settings.recentDays)).onChange((value) => {
        const n = parseInt(value, 10);
        if (!Number.isNaN(n) && n > 0) this.updateSetting("recentDays", n);
      });
    });
    this.markSearchable(recentDays, "\u65F6\u95F4 \u6700\u8FD1N\u5929 \u5929\u6570 \u6700\u8FD1");
    const earliestTime = new import_obsidian3.Setting(bodyEl).setName("\u6700\u65E9\u65F6\u95F4").setDesc("AI \u5DE5\u5177\u53EA\u80FD\u67E5\u770B\u4E0D\u65E9\u4E8E\u8BE5\u65F6\u95F4\u7684\u7B14\u8BB0\uFF08\u683C\u5F0F\u540C\u65F6\u95F4\u6233\u683C\u5F0F\uFF09\uFF1B\u7559\u7A7A\u5219\u4E0D\u9650\u5236\u3002").addText(
      (text) => text.setPlaceholder("\u5982\uFF1A2026-01-01").setValue(this.plugin.settings.earliestTime).onChange((value) => this.updateSetting("earliestTime", value))
    );
    this.markSearchable(earliestTime, "\u65F6\u95F4 \u6700\u65E9\u65F6\u95F4 \u6700\u65E9 \u65F6\u95F4\u9650\u5236");
  }
  // -------------------------------------------------------------------------
  // output (fixed timestamp/source rows + dynamic key→default-value rows)
  // -------------------------------------------------------------------------
  renderOutputGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u8F93\u51FA\u5C5E\u6027", false);
    const timestampProp = new import_obsidian3.Setting(bodyEl).setName("\u65F6\u95F4\u6233\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u5F53\u524D\u65F6\u95F4\u6233\u5C5E\u6027\u540D\uFF1B\u503C\u6309\u300C\u65F6\u95F4\u300D\u9875\u7684\u65F6\u95F4\u6233\u683C\u5F0F\u751F\u6210\u3002").addText(
      (text) => text.setPlaceholder("created").setValue(this.plugin.settings.timestampProperty).onChange((value) => this.updateSetting("timestampProperty", value))
    );
    this.markSearchable(timestampProp, "\u8F93\u51FA\u5C5E\u6027 \u65F6\u95F4\u6233\u5C5E\u6027\u540D created \u65F6\u95F4\u6233");
    const sourceAttr = new import_obsidian3.Setting(bodyEl).setName("\u6765\u6E90\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u6765\u6E90\u8DEF\u5F84\u5C5E\u6027\u540D\u3002").addText(
      (text) => text.setPlaceholder("source").setValue(this.plugin.settings.sourceAttr).onChange((value) => this.updateSetting("sourceAttr", value))
    );
    this.markSearchable(sourceAttr, "\u8F93\u51FA\u5C5E\u6027 \u6765\u6E90\u5C5E\u6027\u540D source \u6765\u6E90");
    const extraEl = bodyEl.createDiv({ cls: "ks-extra-props" });
    this.renderExtraProperties(extraEl);
    const addBtn = new import_obsidian3.Setting(bodyEl).setName("").setDesc("").addButton(
      (btn) => btn.setButtonText("+ \u6DFB\u52A0\u5C5E\u6027").onClick(() => {
        this.plugin.settings.extraProperties.push({ key: "", value: "" });
        void this.plugin.saveSettings();
        this.renderExtraProperties(extraEl);
      })
    );
    this.markSearchable(addBtn, "\u8F93\u51FA\u5C5E\u6027 \u6DFB\u52A0\u5C5E\u6027 \u589E\u52A0 \u6DFB\u52A0");
  }
  /** Render each extra property as a row: key input, value input, delete button. */
  renderExtraProperties(containerEl) {
    containerEl.empty();
    const list = this.plugin.settings.extraProperties || [];
    list.forEach((entry, index) => {
      const row = new import_obsidian3.Setting(containerEl).setName("").setDesc("").addText(
        (text) => text.setPlaceholder("\u5C5E\u6027\u540D").setValue(entry.key).onChange((value) => {
          entry.key = value;
          void this.plugin.saveSettings();
        })
      ).addText(
        (text) => text.setPlaceholder("\u9ED8\u8BA4\u503C").setValue(entry.value).onChange((value) => {
          entry.value = value;
          void this.plugin.saveSettings();
        })
      ).addButton(
        (btn) => btn.setIcon("trash-2").setTooltip("\u5220\u9664").onClick(() => {
          const a = this.plugin.settings.extraProperties;
          a.splice(index, 1);
          void this.plugin.saveSettings();
          this.renderExtraProperties(containerEl);
        })
      );
      row.settingEl.addClass("ks-extra-props-row");
      this.markSearchable(row, `\u8F93\u51FA\u5C5E\u6027 ${entry.key} ${entry.value}`);
    });
  }
  // -------------------------------------------------------------------------
  // test tools (execute the two commands without the command palette)
  // -------------------------------------------------------------------------
  renderTestGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u6D4B\u8BD5\u5DE5\u5177", false);
    const count = new import_obsidian3.Setting(bodyEl).setName("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570").setDesc("\u626B\u63CF\u6E90\u6587\u4EF6\u5939\uFF0C\u7EDF\u8BA1\u6700\u8FD1 N \u5929\u5185\u7684 Markdown \u6587\u4EF6\u6570\u3002").addButton(
      (btn) => btn.setButtonText("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570").setCta().onClick(() => {
        const n = countRecentFiles(this.plugin);
        new import_obsidian3.Notice(`\u6E90\u6587\u4EF6\u5939\u6700\u8FD1 ${this.plugin.settings.recentDays} \u5929\u5171\u6709 ${n} \u4E2A\u6587\u4EF6`);
      })
    );
    this.markSearchable(count, "\u6D4B\u8BD5 \u7EDF\u8BA1 \u6700\u8FD1\u6587\u4EF6\u6570 \u7EDF\u8BA1\u6700\u8FD1 \u7EDF\u8BA1");
    const output = new import_obsidian3.Setting(bodyEl).setName("\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5").setDesc("\u53D6\u6E90\u6587\u4EF6\u5939\u65F6\u95F4\u6700\u65B0\u7684\u6587\u4EF6\uFF0C\u5C06\u5176\u6B63\u6587\u6700\u540E 100 \u5B57\u7B26\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u5939\u3002").addButton(
      (btn) => btn.setButtonText("\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5").setCta().onClick(async () => {
        await outputLatestContent(this.plugin);
      })
    );
    this.markSearchable(output, "\u6D4B\u8BD5 \u8F93\u51FA \u6700\u65B0\u5185\u5BB9 \u8F93\u51FA\u6700\u65B0\u5185\u5BB9 \u8F93\u51FA");
  }
  // -------------------------------------------------------------------------
  // model fetching
  // -------------------------------------------------------------------------
  populateModelDropdown(drop) {
    drop.selectEl.empty();
    if (this.currentModels.length === 0) {
      drop.addOption("", "\uFF08\u8BF7\u5148\u70B9\u51FB\u201C\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B\u201D\uFF09");
      drop.setValue("");
      drop.setDisabled(true);
      return;
    }
    drop.setDisabled(false);
    const options = {};
    for (const model of this.currentModels) options[model] = model;
    drop.addOptions(options);
    const keep = this.plugin.settings.model;
    const value = this.currentModels.includes(keep) ? keep : this.currentModels[0];
    drop.setValue(value);
    this.updateSetting("model", value);
  }
  async refreshModels() {
    const result = await this.plugin.fetchModels(
      this.plugin.settings.apiKey,
      this.plugin.settings.baseUrl
    );
    if (result.ok) {
      this.currentModels = result.modelIds;
      if (this.modelDropdown) this.populateModelDropdown(this.modelDropdown);
    }
  }
};
var KnowledgeSystemSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    renderSettings(this.app, this.plugin, this.containerEl);
  }
};

// src/settingsView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_KS = "knowledge-system-settings-view";
var KnowledgeSettingsView = class extends import_obsidian4.ItemView {
  constructor(plugin, leaf) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_KS;
  }
  getIcon() {
    return "gear";
  }
  getDisplayText() {
    return "Knowledge System";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("ks-view");
    renderSettings(this.app, this.plugin, container);
  }
  async onClose() {
    this.contentEl.empty();
  }
};

// src/chatView.ts
var import_obsidian5 = require("obsidian");

// src/utils/tools.ts
var DAY_MS2 = 864e5;
var FALLBACK_FORMATS2 = ["YYYY-MM-DD", "YYYY.MM.DD", "YYYY/MM/DD"];
var ANTHROPIC_TOOLS = [
  {
    name: "list_recent_notes",
    description: "\u5217\u51FA\u6E90\u6587\u4EF6\u5939\u5185\u6700\u8FD1 N \u5929\u7684 Markdown \u7B14\u8BB0\uFF08\u6807\u9898 + \u65F6\u95F4\uFF09\u3002",
    input_schema: {
      type: "object",
      properties: { days: { type: "integer", description: "\u56DE\u770B\u5929\u6570\uFF1B\u7F3A\u7701\u7528\u8BBE\u7F6E\u7684\u6700\u8FD1 N \u5929" } },
      required: []
    }
  },
  {
    name: "read_note",
    description: "\u8BFB\u53D6\u6E90\u6587\u4EF6\u5939\u5185\u67D0\u7BC7\u7B14\u8BB0\u7684\u6B63\u6587\uFF08\u53BB\u9664 YAML frontmatter\uFF09\u3002",
    input_schema: {
      type: "object",
      properties: { name: { type: "string", description: "\u7B14\u8BB0\u6587\u4EF6\u540D\uFF08\u53EF\u5E26\u6216\u4E0D\u5E26 .md \u540E\u7F00\uFF09" } },
      required: ["name"]
    }
  },
  {
    name: "create_note",
    description: "\u5728\u8F93\u51FA\u6587\u4EF6\u5939\u521B\u5EFA\u4E00\u7BC7\u65B0\u7B14\u8BB0\u3002",
    input_schema: {
      type: "object",
      properties: {
        title: { type: "string", description: "\u6587\u4EF6\u540D\uFF08\u4E0D\u542B .md \u540E\u7F00\uFF09" },
        yaml: { type: "object", description: "frontmatter \u952E\u503C\u5BF9" },
        content: { type: "string", description: "\u6B63\u6587" }
      },
      required: ["title"]
    }
  }
];
function stripExt(name) {
  return (name || "").replace(/\.md$/i, "");
}
function inFolder(path, folder) {
  const f = (folder || "/").trim();
  if (f === "/" || f === "") return true;
  return path.startsWith(f + "/");
}
function parseEarliest(value, format, zeit) {
  const s = (value || "").trim();
  if (!s) return null;
  const m = zeit(s, format, true);
  if (m && typeof m.isValid === "function" && m.isValid()) return m.valueOf();
  return null;
}
function fileTimestamp(file, ctx) {
  var _a, _b, _c, _d, _e, _f;
  const settings = ctx.settings;
  const zeit = (_a = ctx.moment) != null ? _a : typeof window !== "undefined" ? window.moment : null;
  const prop = (settings.timeAttr || "").trim();
  const fm = (_d = (_c = (_b = ctx.app.metadataCache.getFileCache(file)) == null ? void 0 : _b.frontmatter) != null ? _c : file == null ? void 0 : file.frontmatter) != null ? _d : {};
  if (prop && fm && fm[prop] != null) {
    const formats = [settings.timeFormat, ...FALLBACK_FORMATS2].filter(
      (f, i, arr) => !!f && arr.indexOf(f) === i
    );
    for (const format of formats) {
      const m = zeit(String(fm[prop]), format, true);
      if (m && typeof m.isValid === "function" && m.isValid()) return m.valueOf();
    }
  }
  return (_f = (_e = file == null ? void 0 : file.stat) == null ? void 0 : _e.ctime) != null ? _f : 0;
}
function isValidFilename(title) {
  const t = (title || "").trim();
  if (!t) return false;
  if (t === "." || t === "..") return false;
  if (/[/\\]/.test(t)) return false;
  if (/\.\./.test(t)) return false;
  if (/^[A-Za-z]:/.test(t)) return false;
  if (/^\//.test(t)) return false;
  return true;
}
function joinVaultPath(folder, name) {
  const base = (folder || "/").trim() === "/" ? "" : (folder || "").trim().replace(/^\/+|\/+$/g, "");
  return (base ? base + "/" + name : name).replace(/\/+/g, "/").replace(/^\/+/, "");
}
function serializeYaml(yaml) {
  if (yaml == null) return "";
  if (typeof yaml === "string") return yaml.trim().replace(/^\n+|\n+$/g, "");
  if (typeof yaml === "object") {
    return Object.entries(yaml).map(([k, v]) => `${k}: ${v == null ? "" : v}`).join("\n");
  }
  return "";
}
async function listRecentNotesTool(ctx, args) {
  var _a, _b, _c, _d, _e, _f, _g, _h;
  const settings = ctx.settings;
  const now = (_a = ctx.now) != null ? _a : Date.now();
  const zeit = (_b = ctx.moment) != null ? _b : typeof window !== "undefined" ? window.moment : null;
  const days = typeof (args == null ? void 0 : args.days) === "number" ? args.days : (_c = settings.recentDays) != null ? _c : 7;
  const folder = (settings.sourceFolder || "/").trim();
  const earliest = parseEarliest((_d = settings.earliestTime) != null ? _d : "", (_e = settings.timeFormat) != null ? _e : "", zeit);
  const files = (_h = (_g = (_f = ctx.app.vault).getMarkdownFiles) == null ? void 0 : _g.call(_f)) != null ? _h : [];
  const entries = files.filter((f) => inFolder(f.path, folder)).map((f) => {
    var _a2, _b2;
    return { f, ts: fileTimestamp(f, ctx), ctime: (_b2 = (_a2 = f == null ? void 0 : f.stat) == null ? void 0 : _a2.ctime) != null ? _b2 : 0 };
  });
  if (earliest != null && entries.some((e) => e.ts < earliest)) {
    return { error: `ERROR: \u5FEB\u7167\u66F4\u65E9\u4E8E\u6700\u65E9\u65F6\u95F4 ${settings.earliestTime}` };
  }
  const cutoff = Math.max(now - Math.max(1, Math.floor(days)) * DAY_MS2, earliest != null ? earliest : -Infinity);
  const recent = entries.filter((e) => e.ts >= cutoff);
  recent.sort((a, b) => b.ts - a.ts || a.ctime - b.ctime);
  return {
    result: recent.map((e) => {
      var _a2, _b2;
      return { title: stripExt((_b2 = (_a2 = e.f.basename) != null ? _a2 : e.f.name) != null ? _b2 : e.f.path), timestamp: e.ts };
    })
  };
}
async function readNoteTool(ctx, args) {
  var _a, _b, _c, _d, _e, _f, _g, _h;
  const settings = ctx.settings;
  const zeit = (_a = ctx.moment) != null ? _a : typeof window !== "undefined" ? window.moment : null;
  const folder = (settings.sourceFolder || "/").trim();
  const target = stripExt(((args == null ? void 0 : args.name) || "").trim());
  if (!target) return { error: "ERROR: \u672A\u63D0\u4F9B\u6587\u4EF6\u540D" };
  const files = (_d = (_c = (_b = ctx.app.vault).getMarkdownFiles) == null ? void 0 : _c.call(_b)) != null ? _d : [];
  const match = files.find(
    (f) => {
      var _a2, _b2;
      return inFolder(f.path, folder) && stripExt((_b2 = (_a2 = f.basename) != null ? _a2 : f.name) != null ? _b2 : f.path) === target;
    }
  );
  if (!match) return { error: "ERROR: \u672A\u627E\u5230\u7B14\u8BB0" };
  const ts = fileTimestamp(match, ctx);
  const earliest = parseEarliest((_e = settings.earliestTime) != null ? _e : "", (_f = settings.timeFormat) != null ? _f : "", zeit);
  if (earliest != null && ts < earliest) return { error: `ERROR: \u7B14\u8BB0\u65E9\u4E8E\u6700\u65E9\u65F6\u95F4 ${settings.earliestTime}` };
  const raw = await ctx.app.vault.read(match);
  return { result: { title: stripExt((_h = (_g = match.basename) != null ? _g : match.name) != null ? _h : match.path), content: stripFrontmatter(raw) } };
}
async function createNoteTool(ctx, args) {
  var _a;
  const settings = ctx.settings;
  const title = ((args == null ? void 0 : args.title) || "").trim();
  if (!isValidFilename(title)) return { error: "ERROR: \u975E\u6CD5\u6587\u4EF6\u540D" };
  const folder = (settings.outputFolder || "/").trim();
  const name = title.toLowerCase().endsWith(".md") ? title : title + ".md";
  const path = joinVaultPath(folder, name);
  const yamlStr = serializeYaml(args == null ? void 0 : args.yaml);
  const body = `${(_a = args == null ? void 0 : args.content) != null ? _a : ""}`;
  const full = yamlStr ? `---
${yamlStr}
---
${body}` : `---
---
${body}`;
  await ctx.app.vault.create(path, full);
  return { result: { path } };
}

// src/chatView.ts
var VIEW_TYPE_CHAT = "knowledge-system-chat-view";
var TEST_PROMPT = "\u8BF7\u6309\u987A\u5E8F\u5B8C\u6210\u4EE5\u4E0B\u4EFB\u52A1\uFF0C\u5E76\u5728\u6BCF\u4E00\u6B65\u7B80\u8981\u8BF4\u660E\u4F60\u7684\u601D\u8003\u4E0E\u4F9D\u636E\uFF1A\n\u7B2C\u4E00\u6B65\uFF1A\u8C03\u7528 list_recent_notes \u67E5\u770B\u6E90\u6587\u4EF6\u5939\u6700\u8FD1\u51E0\u5929\u7684\u7B14\u8BB0\uFF1B\n\u7B2C\u4E8C\u6B65\uFF1A\u4ECE\u4E2D\u9009\u62E9\u4E00\u7BC7\u7B14\u8BB0\u5E76\u8C03\u7528 read_note \u9605\u8BFB\u5B83\u7684\u6B63\u6587\uFF1B\n\u7B2C\u4E09\u6B65\uFF1A\u8C03\u7528 create_note \u5728\u8F93\u51FA\u6587\u4EF6\u5939\u521B\u5EFA\u4E00\u7BC7\u603B\u7ED3\u7B14\u8BB0\uFF08frontmatter \u5305\u542B \u6765\u6E90 source\u3001\u5206\u7C7B category\u3001\u5BA1\u6838\u72B6\u6001 approved\uFF09\u3002";
function emptyBlock(type) {
  return { type, text: "", thinking: "", signature: "", id: "", name: "", input: {}, partialJson: "" };
}
function blocksToApi(blocks) {
  return blocks.map(
    (b) => b.type === "tool_use" ? { type: "tool_use", id: b.id, name: b.name, input: b.input } : b.type === "thinking" ? { type: "thinking", thinking: b.thinking, signature: b.signature } : { type: "text", text: b.text }
  );
}
function truncate(s, n) {
  const cps = [...s != null ? s : ""];
  return cps.length > n ? cps.slice(0, n).join("") + "\u2026\u622A\u65AD" : s;
}
function summarizeInput(input) {
  try {
    return JSON.stringify(input != null ? input : {});
  } catch (e) {
    return String(input);
  }
}
var KnowledgeChatView = class extends import_obsidian5.ItemView {
  constructor(plugin, leaf) {
    super(leaf);
    this.apiHistory = [];
    this.busy = false;
    this.activeController = null;
    this.turnBlocks = [];
    this.turnStopReason = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getIcon() {
    return "message-square";
  }
  getDisplayText() {
    return "Knowledge System Chat";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("ks-chat");
    this.scrollEl = container.createDiv({ cls: "ks-chat-scroll" });
    const bar = container.createDiv({ cls: "ks-chat-inputbar" });
    this.inputEl = bar.createEl("textarea", { cls: "ks-chat-textarea" });
    this.inputEl.placeholder = "\u8F93\u5165\u6D88\u606F\u2026\uFF08Enter \u53D1\u9001 / Shift+Enter \u6362\u884C\uFF09";
    this.inputEl.addEventListener("keydown", (ev) => {
      if (ev.key === "Enter" && !ev.shiftKey) {
        ev.preventDefault();
        void this.send();
      }
    });
    const sendBtn = bar.createEl("button", { cls: "mod-cta ks-chat-send" });
    (0, import_obsidian5.setIcon)(sendBtn, "send");
    sendBtn.addEventListener("click", () => void this.send());
    const testBtn = bar.createEl("button", { cls: "ks-chat-test" });
    (0, import_obsidian5.setIcon)(testBtn, "play");
    testBtn.setAttribute("title", "\u6D4B\u8BD5\u4EFB\u52A1");
    testBtn.addEventListener("click", () => void this.send(TEST_PROMPT));
  }
  async onClose() {
    var _a;
    (_a = this.activeController) == null ? void 0 : _a.abort();
    this.contentEl.empty();
  }
  // -------------------------------------------------------------------------
  // send / render helpers
  // -------------------------------------------------------------------------
  userBubble(text) {
    const el = this.scrollEl.createDiv({ cls: "ks-chat-msg ks-chat-user" }).createDiv({ cls: "ks-chat-content" });
    el.style.whiteSpace = "pre-wrap";
    el.setText(text);
    return el;
  }
  assistantBubble() {
    const root = this.scrollEl.createDiv({ cls: "ks-chat-msg ks-chat-ai" });
    const body = root.createDiv({ cls: "ks-chat-content markdown-rendered" });
    return { root, body };
  }
  /** Render a copyable, self-diagnosing error block (used by every failure path). */
  errorBlock(streamErr, nonStreamErr) {
    const root = this.scrollEl.createDiv({ cls: "ks-chat-msg ks-chat-error" });
    const block = root.createDiv({ cls: "ks-chat-error-block" });
    const pre = block.createEl("pre", { cls: "ks-chat-error-text" });
    const lines = ["\u8BF7\u6C42\u5931\u8D25"];
    if (streamErr) lines.push(`\u6D41\u5F0F\uFF1A${streamErr}`);
    if (nonStreamErr) lines.push(`\u975E\u6D41\u5F0F\uFF1A${nonStreamErr}`);
    lines.push(`\u63D0\u793A\uFF1A${this.errorHint()}`);
    const text = lines.join("\n");
    pre.setText(text);
    const copyBtn = block.createEl("button", { cls: "ks-chat-copy ks-chat-copy-btn" });
    copyBtn.setText("\u4E00\u952E\u590D\u5236");
    copyBtn.addEventListener("click", () => this.copyToClipboard(text, copyBtn));
  }
  /** Build the diagnostic hint line from the current base URL configuration. */
  errorHint() {
    const base = (this.plugin.settings.baseUrl || "").trim();
    if (hasAnthropicPath(base)) {
      return "\u8BF7\u68C0\u67E5 API Key\u3001\u6A21\u578B\u540D\u4E0E\u7F51\u7EDC\u8FDE\u63A5\u3002";
    }
    const attemptedAnthropic = !hasAnthropicPath(base) && chatEndpointCandidates(base).length > 1;
    if (attemptedAnthropic) {
      return "\u5DF2\u81EA\u52A8\u5C1D\u8BD5\u8865\u5145 /anthropic \u524D\u7F00\u4ECD\u672A\u6210\u529F\u3002\u82E5\u4F7F\u7528 DeepSeek \u5B98\u65B9 API\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u5C06 Base URL \u6539\u4E3A https://api.deepseek.com/anthropic\uFF08\u6216\u4FDD\u6301\u6839\u5730\u5740\uFF0C\u672C\u7248\u672C\u6BCF\u6B21\u90FD\u4F1A\u81EA\u52A8\u63A2\u6D4B\u4FEE\u6B63\uFF09\u3002";
    }
    return "\u8BF7\u68C0\u67E5 API Key\u3001\u6A21\u578B\u540D\u4E0E\u7F51\u7EDC\u8FDE\u63A5\u3002";
  }
  /** Copy `text` to the clipboard, keeping the UI under `btn` in sync. */
  copyToClipboard(text, btn) {
    if (navigator.clipboard && typeof navigator.clipboard.writeText === "function") {
      navigator.clipboard.writeText(text).then(
        () => this.markCopied(btn),
        () => this.clipboardFallback(text, btn)
      );
    } else {
      this.clipboardFallback(text, btn);
    }
  }
  /** Flip the button to「已复制」then back to「一键复制」(short-lived confirmation). */
  markCopied(btn) {
    btn.setText("\u5DF2\u590D\u5236");
    window.setTimeout(() => btn.setText("\u4E00\u952E\u590D\u5236"), 1500);
  }
  /** Legacy textarea+execCommand fallback; request the user to select on failure. */
  clipboardFallback(text, btn) {
    try {
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.top = "0";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      this.markCopied(btn);
    } catch (e) {
      btn.setText("\u590D\u5236\u5931\u8D25\uFF0C\u8BF7\u957F\u6309\u6587\u672C");
    }
  }
  /** Persist an endpoint auto-correction and notify the user (explicit, not silent). */
  handleAutoCorrect(url) {
    const corrected = url.replace(/\/v1\/messages$/, "").replace(/\/+$/, "");
    this.plugin.settings.baseUrl = corrected;
    void this.plugin.saveSettings();
    new import_obsidian5.Notice(`\u5DF2\u81EA\u52A8\u66F4\u6B63\u7AEF\u70B9\uFF1A${url}\uFF08\u8BBE\u7F6E\u4E2D\u7684 Base URL \u5DF2\u540C\u6B65\u66F4\u65B0\uFF09`);
  }
  async send(text) {
    var _a, _b;
    if (this.busy) return;
    const userText = (text != null ? text : this.inputEl.value).trim();
    if (!userText) return;
    this.inputEl.value = "";
    (_a = this.activeController) == null ? void 0 : _a.abort();
    this.busy = true;
    try {
      this.apiHistory.push({ role: "user", content: userText });
      this.userBubble(userText);
      await this.runTurn();
    } catch (e) {
      this.errorBlock("\u8BF7\u6C42\u5F02\u5E38\uFF1A" + ((_b = e == null ? void 0 : e.message) != null ? _b : "\u672A\u77E5\u9519\u8BEF"), null);
    } finally {
      this.busy = false;
      this.activeController = null;
      this.scrollEl.scrollTop = this.scrollEl.scrollHeight;
    }
  }
  async runTurn() {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const { body } = this.assistantBubble();
    this.turnBlocks = [];
    this.turnStopReason = null;
    this.turnError = void 0;
    const ac = new AbortController();
    this.activeController = ac;
    let streamOk = false;
    let streamErr = null;
    try {
      const st = await streamAnthropicMessages(this.plugin.settings, this.apiHistory, {
        tools: ANTHROPIC_TOOLS,
        signal: ac.signal,
        onEvent: (event) => this.handleChatEvent(body, event),
        onAutoCorrect: (url) => this.handleAutoCorrect(url)
      });
      if (st.ok) {
        streamOk = true;
      } else {
        streamErr = st.status != null ? `HTTP ${st.status}\uFF08POST ${(_a = st.url) != null ? _a : "\u672A\u77E5"}\uFF09` : (_b = st.error) != null ? _b : "\u7F51\u7EDC\u9519\u8BEF";
      }
    } catch (e) {
      streamErr = (_c = e == null ? void 0 : e.message) != null ? _c : "\u7F51\u7EDC\u9519\u8BEF";
    } finally {
      this.activeController = null;
    }
    if (streamOk) {
      if (this.turnError) {
        this.errorBlock(this.turnError, null);
        return;
      }
      await this.finishTurn(body, this.turnBlocks.filter(Boolean), this.turnStopReason);
      return;
    }
    let res;
    let nonStreamErr = null;
    try {
      res = await fetchAnthropicMessages(this.plugin.settings, this.apiHistory, {
        tools: ANTHROPIC_TOOLS,
        onAutoCorrect: (url) => this.handleAutoCorrect(url)
      });
      if (res.requestError != null) {
        nonStreamErr = `\u7F51\u7EDC\u9519\u8BEF\uFF08POST ${(_d = res.url) != null ? _d : "\u672A\u77E5"}\uFF09\uFF1A${res.requestError}`;
      } else if (res.status < 200 || res.status >= 300) {
        nonStreamErr = `HTTP ${res.status}\uFF08POST ${(_e = res.url) != null ? _e : "\u672A\u77E5"}\uFF09`;
      }
    } catch (e) {
      nonStreamErr = `\u7F51\u7EDC\u9519\u8BEF\uFF08POST ${(_f = res == null ? void 0 : res.url) != null ? _f : "\u672A\u77E5"}\uFF09\uFF1A${(_g = e == null ? void 0 : e.message) != null ? _g : "\u672A\u77E5"}`;
    }
    if (res && res.status >= 200 && res.status < 300) {
      let json = null;
      try {
        json = JSON.parse(res.text);
      } catch (e) {
        json = null;
      }
      const parsed = parseAnthropicResponse(json);
      await this.finishTurn(body, parsed.blocks, (_h = parsed.stop_reason) != null ? _h : null);
      return;
    }
    this.errorBlock(streamErr, nonStreamErr);
  }
  handleChatEvent(body, ev) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p;
    const d = ev.data;
    if (!d || typeof d !== "object") return;
    if (d.type === "error") {
      this.turnError = `\u9519\u8BEF\uFF1A${(_c = (_b = (_a = d.error) == null ? void 0 : _a.message) != null ? _b : d.message) != null ? _c : "\u672A\u77E5"}`;
      return;
    }
    if (d.type === "content_block_start") {
      const cb = (_d = d.content_block) != null ? _d : {};
      const idx = (_e = d.index) != null ? _e : 0;
      this.turnBlocks[idx] = emptyBlock((_f = cb.type) != null ? _f : "text");
      this.turnBlocks[idx].id = (_g = cb.id) != null ? _g : "";
      this.turnBlocks[idx].name = (_h = cb.name) != null ? _h : "";
      if (cb.type === "thinking") this.turnBlocks[idx].signature = (_i = cb.signature) != null ? _i : "";
    } else if (d.type === "content_block_delta") {
      const blk = this.turnBlocks[d.index];
      const delta = (_j = d.delta) != null ? _j : {};
      if (!blk) return;
      if (delta.type === "text_delta") blk.text += (_k = delta.text) != null ? _k : "";
      else if (delta.type === "thinking_delta") blk.thinking += (_l = delta.thinking) != null ? _l : "";
      else if (delta.type === "signature_delta") blk.signature += (_m = delta.signature) != null ? _m : "";
      else if (delta.type === "input_json_delta") blk.partialJson += (_n = delta.partial_json) != null ? _n : "";
    } else if (d.type === "content_block_stop") {
      const blk = this.turnBlocks[d.index];
      if (blk && blk.partialJson) {
        try {
          blk.input = JSON.parse(blk.partialJson);
        } catch (e) {
          blk.input = blk.partialJson;
        }
      }
    } else if (d.type === "message_delta") {
      this.turnStopReason = (_p = (_o = d.delta) == null ? void 0 : _o.stop_reason) != null ? _p : null;
    }
    this.renderBlocks(body, this.turnBlocks.filter(Boolean), {});
  }
  async finishTurn(body, blocks, stopReason) {
    this.renderBlocks(body, blocks, {});
    if (stopReason === "tool_use") {
      const ctx = { app: this.plugin.app, settings: this.plugin.settings, moment: window.moment };
      const toolResults = {};
      for (const b of blocks.filter((x) => x.type === "tool_use")) {
        toolResults[b.id] = await this.executeTool(ctx, b.name, b.input);
      }
      this.renderBlocks(body, blocks, toolResults);
      this.apiHistory.push({ role: "assistant", content: blocksToApi(blocks) });
      this.apiHistory.push({
        role: "user",
        content: Object.keys(toolResults).map((id) => ({ type: "tool_result", tool_use_id: id, content: toolResults[id] }))
      });
      await this.runTurn();
    } else {
      this.apiHistory.push({ role: "assistant", content: blocksToApi(blocks) });
    }
  }
  renderBlocks(body, blocks, toolResults) {
    body.empty();
    for (const block of blocks) {
      if (block.type === "thinking") {
        this.renderThinking(body, block.thinking);
      } else if (block.type === "text") {
        const el = body.createDiv({ cls: "ks-chat-markdown markdown-rendered" });
        void import_obsidian5.MarkdownRenderer.render(this.app, block.text, el, "", this);
      } else if (block.type === "tool_use") {
        this.renderToolCard(body, block, toolResults[block.id]);
      }
    }
  }
  renderThinking(body, thinking) {
    const wrap = body.createDiv({ cls: "ks-think is-collapsed" });
    const head = wrap.createDiv({ cls: "ks-think-head" });
    const chev = head.createSpan({ cls: "ks-think-icon" });
    (0, import_obsidian5.setIcon)(chev, "chevron-right");
    head.createSpan({ cls: "ks-think-label", text: "\u601D\u8003\u4E2D" });
    const contentEl = wrap.createDiv({ cls: "ks-think-body" });
    contentEl.setText(thinking);
    head.addEventListener("click", () => {
      const collapsed = wrap.hasClass("is-collapsed");
      wrap.toggleClass("is-collapsed", !collapsed);
      (0, import_obsidian5.setIcon)(chev, collapsed ? "chevron-down" : "chevron-right");
    });
  }
  renderToolCard(body, block, result) {
    const card = body.createDiv({ cls: "ks-tool-card" });
    const title = card.createDiv({ cls: "ks-tool-name" });
    (0, import_obsidian5.setIcon)(title.createSpan({ cls: "ks-tool-icon" }), "wrench");
    title.createSpan({ text: block.name || "tool" });
    card.createDiv({ cls: "ks-tool-input", text: summarizeInput(block.input) });
    const resultEl = card.createDiv({ cls: "ks-tool-result" });
    resultEl.setText(result == null ? "\u6267\u884C\u4E2D\u2026" : truncate(result, 300));
  }
  async executeTool(ctx, name, input) {
    var _a;
    const a = input != null ? input : {};
    try {
      if (name === "list_recent_notes") {
        const r = await listRecentNotesTool(ctx, { days: a.days });
        return "error" in r ? `ERROR: ${r.error}` : JSON.stringify(r.result);
      }
      if (name === "read_note") {
        const r = await readNoteTool(ctx, { name: a.name });
        return "error" in r ? `ERROR: ${r.error}` : r.result.content;
      }
      if (name === "create_note") {
        const r = await createNoteTool(ctx, { title: a.title, yaml: a.yaml, content: a.content });
        return "error" in r ? `ERROR: ${r.error}` : `\u5DF2\u521B\u5EFA\uFF1A${r.result.path}`;
      }
      return `ERROR: \u672A\u77E5\u5DE5\u5177 ${name}`;
    } catch (e) {
      return `ERROR: ${(_a = e == null ? void 0 : e.message) != null ? _a : "\u5DE5\u5177\u6267\u884C\u5931\u8D25"}`;
    }
  }
};

// src/main.ts
var KnowledgeSystemPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new KnowledgeSystemSettingTab(this.app, this));
    this.registerView(VIEW_TYPE_KS, (leaf) => new KnowledgeSettingsView(this, leaf));
    this.registerView(VIEW_TYPE_CHAT, (leaf) => new KnowledgeChatView(this, leaf));
    this.addCommand({
      id: "show-knowledge-system-settings-view",
      name: "Show Knowledge System settings view",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "open-knowledge-chat-view",
      name: "Open Knowledge System chat",
      callback: () => {
        void this.activateChatView();
      }
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_KS);
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHAT);
  }
  /** Open the standalone settings view in a new tab leaf. */
  async activateView() {
    if (typeof this.app.workspace.detachLeavesOfType === "function") {
      this.app.workspace.detachLeavesOfType(VIEW_TYPE_KS);
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_KS, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  /** Open the chat view in a new tab leaf. */
  async activateChatView() {
    if (typeof this.app.workspace.detachLeavesOfType === "function") {
      this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHAT);
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  /**
   * Issue one Anthropic-compatible chat request (POST {baseUrl}/v1/messages,
   * stream). Exposed so the acceptance harness can assert the protocol headers /
   * endpoint without using the chat UI. Returns the response status + body text.
   */
  async streamChat(messages) {
    return fetchAnthropicMessages(this.settings, messages, { tools: ANTHROPIC_TOOLS });
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    this.migrateLegacyOutputProps();
  }
  /**
   * Move the legacy `reviewAttr`/`categoryAttr` output attributes into the new
   * `extraProperties` list the first time the plugin loads (only when the
   * dynamic list is empty). The old fields are kept for read compat.
   */
  migrateLegacyOutputProps() {
    this.settings.extraProperties = migrateExtraProperties(this.settings);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Fetch the provider's model list (GET /models). Exposed publicly so the
   * settings tab button and the harness both call it. On success the returned
   * ids are persisted onto the settings.
   */
  async fetchModels(apiKey, baseUrl) {
    const result = await fetchModelList(
      apiKey || this.settings.apiKey,
      baseUrl || this.settings.baseUrl
    );
    if (result.ok) {
      this.settings.models = result.modelIds;
      if (result.modelIds.length > 0) this.settings.model = result.modelIds[0];
      await this.saveSettings();
    }
    return result;
  }
};
