/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KnowledgeSystemPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  baseUrl: "https://api.deepseek.com",
  model: "",
  models: [],
  sourceFolder: "/",
  outputFolder: "/",
  timeAttr: "",
  timeFormat: "YYYY-MM-DD",
  recentDays: 7,
  reviewAttr: "approved",
  reviewDefault: "\u672A\u5BA1",
  categoryAttr: "category",
  categoryDefault: "\u672A\u5206\u7C7B",
  timestampProperty: "created",
  sourceAttr: "source",
  customApiKey: "",
  customModel: "",
  extraProperties: []
};

// src/settingsTab.ts
var import_obsidian3 = require("obsidian");

// src/folderSuggest.ts
var import_obsidian = require("obsidian");
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const folders = [];
    const lower = (query || "").toLowerCase();
    const visit = (f) => {
      folders.push(f);
      f.children.forEach((c) => {
        if (c instanceof import_obsidian.TFolder) visit(c);
      });
    };
    this.app.vault.getAllLoadedFiles().forEach((f) => {
      if (f instanceof import_obsidian.TFolder) visit(f);
    });
    return folders.filter((f) => f.path.toLowerCase().includes(lower)).slice(0, 50);
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path || "/");
  }
  selectSuggestion(folder) {
    this.inputEl.value = folder.path || "/";
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/core.ts
var import_obsidian2 = require("obsidian");

// src/utils/index.ts
var DAY_MS = 864e5;
function parseTimestamp(value, moment, formats) {
  if (typeof value === "number") return value > 1e12 ? value : value * 1e3;
  if (value instanceof Date) return value.getTime();
  if (typeof value !== "string") return null;
  const s = value.trim();
  if (!s) return null;
  for (const f of formats) {
    if (!f) continue;
    const m = moment(s, f, true);
    if (m && typeof m.isValid === "function" && m.isValid()) return m.valueOf();
  }
  return null;
}
function resolveTimestamp(frontmatter, ctimeMs, moment, timeAttr, formats) {
  if (timeAttr) {
    const v = frontmatter[timeAttr];
    if (v !== void 0 && v !== null) {
      const ts = parseTimestamp(v, moment, formats);
      if (ts !== null) return ts;
    }
  }
  return ctimeMs;
}
function countRecent(items, opts) {
  const { moment, timeAttr, formats, nowMs, days } = opts;
  const cutoff = nowMs - Math.max(1, Math.floor(days || 1)) * DAY_MS;
  let n = 0;
  for (const item of items) {
    if (!item.isMd) continue;
    const ts = resolveTimestamp(item.frontmatter, item.ctimeMs, moment, timeAttr, formats);
    if (ts >= cutoff) n++;
  }
  return n;
}
function extractLastChars(text, n) {
  return [...text].slice(-n).join("");
}
function buildFrontmatter(vals, cfg) {
  const lines = [
    `${cfg.timestampProperty}: ${cfg.moment(vals.timestampMs).format(cfg.timeFormat)}`,
    `${cfg.sourceAttr}: ${vals.source}`
  ];
  const extra = cfg.extraProperties && cfg.extraProperties.length > 0 ? cfg.extraProperties : null;
  if (extra) {
    for (const { key, value } of extra) lines.push(`${key}: ${value}`);
  } else {
    if (cfg.reviewAttr && cfg.reviewDefault != null) lines.push(`${cfg.reviewAttr}: ${cfg.reviewDefault}`);
    if (cfg.categoryAttr && cfg.categoryDefault != null) lines.push(`${cfg.categoryAttr}: ${cfg.categoryDefault}`);
  }
  return lines.join("\n");
}
function migrateExtraProperties(input) {
  const extra = input.extraProperties;
  if (Array.isArray(extra) && extra.length > 0) {
    return extra.map((e) => {
      var _a, _b;
      const item = e;
      return { key: String((_a = item == null ? void 0 : item.key) != null ? _a : ""), value: String((_b = item == null ? void 0 : item.value) != null ? _b : "") };
    });
  }
  const out = [];
  const reviewAttr = input.reviewAttr;
  const reviewDefault = input.reviewDefault;
  if (reviewAttr && reviewDefault != null) out.push({ key: String(reviewAttr), value: String(reviewDefault) });
  const categoryAttr = input.categoryAttr;
  const categoryDefault = input.categoryDefault;
  if (categoryAttr && categoryDefault != null) out.push({ key: String(categoryAttr), value: String(categoryDefault) });
  return out;
}
function stripFrontmatter(content) {
  if (content.startsWith("---")) {
    const idx = content.indexOf("\n---", 3);
    if (idx >= 0) {
      let rest = content.slice(idx + 4);
      if (rest.startsWith("\n")) rest = rest.slice(1);
      return rest;
    }
  }
  return content;
}

// src/core.ts
var FALLBACK_FORMATS = ["YYYY-MM-DD", "YYYY.MM.DD", "YYYY/MM/DD"];
function formatsFor(plugin) {
  const f = (plugin.settings.timeFormat || "").trim();
  return [f, ...FALLBACK_FORMATS].filter((x, i, arr) => !!x && arr.indexOf(x) === i);
}
function frontmatterOf(app, file) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  return (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
}
function bodySnippet(body) {
  if (body == null) return "";
  const text = typeof body === "string" ? body : JSON.stringify(body);
  return text.slice(0, 100);
}
function resolveSourceFolder(plugin) {
  const raw = (plugin.settings.sourceFolder || "/").trim();
  if (raw === "/" || raw === "") return vaultRoot(plugin.app);
  const p = raw.replace(/^\/+|\/+$/g, "");
  const found = plugin.app.vault.getAbstractFileByPath(p);
  return found instanceof import_obsidian2.TFolder ? found : vaultRoot(plugin.app);
}
function vaultRoot(app) {
  var _a;
  const vault = app.vault;
  if (typeof vault.getRoot === "function") {
    const r = vault.getRoot();
    if (r instanceof import_obsidian2.TFolder) return r;
  }
  const byEmpty = app.vault.getAbstractFileByPath("");
  return byEmpty instanceof import_obsidian2.TFolder ? byEmpty : (_a = vault.getRoot) == null ? void 0 : _a.call(vault);
}
function getMarkdownFilesInFolder(folder) {
  const result = [];
  const visit = (f) => {
    for (const child of f.children) {
      if (child instanceof import_obsidian2.TFile && child.extension === "md") {
        result.push(child);
      } else if (child instanceof import_obsidian2.TFolder) {
        visit(child);
      }
    }
  };
  visit(folder);
  return result;
}
function countRecentFiles(plugin) {
  const folder = resolveSourceFolder(plugin);
  const files = getMarkdownFilesInFolder(folder);
  const items = files.map((file) => ({
    isMd: true,
    frontmatter: frontmatterOf(plugin.app, file),
    ctimeMs: file.stat.ctime
  }));
  const count = countRecent(items, {
    moment: window.moment,
    timeAttr: plugin.settings.timeAttr || "",
    formats: formatsFor(plugin),
    nowMs: Date.now(),
    days: plugin.settings.recentDays
  });
  new import_obsidian2.Notice(`\u6E90\u6587\u4EF6\u5939\u6700\u8FD1 ${plugin.settings.recentDays} \u5929\u5171\u6709 ${count} \u4E2A\u6587\u4EF6`);
  return count;
}
function joinOutputPath(folder, name) {
  const raw = (folder || "/").trim();
  const base = raw === "/" || raw === "" ? "" : raw.replace(/^\/+|\/+$/g, "");
  const joined = base ? `${base}/${name}` : name;
  return joined.replace(/\/+/g, "/").replace(/^\/+/, "");
}
async function ensureFolderExists(app, folder) {
  const raw = (folder || "/").trim();
  const parts = (raw === "/" || raw === "" ? "" : raw.replace(/^\/+|\/+$/g, "")).split("/").filter(Boolean);
  let cur = "";
  for (const part of parts) {
    cur = cur ? `${cur}/${part}` : part;
    if (!app.vault.getAbstractFileByPath(cur)) {
      await app.vault.createFolder(cur);
    }
  }
}
async function outputLatestContent(plugin) {
  const folder = resolveSourceFolder(plugin);
  const files = getMarkdownFilesInFolder(folder);
  if (files.length === 0) {
    new import_obsidian2.Notice("\u6E90\u6587\u4EF6\u5939\u4E2D\u6CA1\u6709\u53EF\u7528\u7684 Markdown \u6587\u4EF6");
    return "";
  }
  const formats = formatsFor(plugin);
  const timeAttr = plugin.settings.timeAttr || "";
  const tsOf = (file) => resolveTimestamp(frontmatterOf(plugin.app, file), file.stat.ctime, window.moment, timeAttr, formats);
  let latest = files[0];
  let latestTs = tsOf(latest);
  for (const file of files) {
    const ts = tsOf(file);
    if (ts > latestTs) {
      latestTs = ts;
      latest = file;
    }
  }
  const raw = await plugin.app.vault.read(latest);
  const body = stripFrontmatter(raw);
  const last100 = extractLastChars(body, 100);
  const now = window.moment();
  const frontmatter = buildFrontmatter(
    { source: latest.path, timestampMs: now.valueOf() },
    {
      timestampProperty: plugin.settings.timestampProperty,
      sourceAttr: plugin.settings.sourceAttr || "source",
      moment: window.moment,
      timeFormat: plugin.settings.timeFormat,
      extraProperties: plugin.settings.extraProperties,
      reviewAttr: plugin.settings.reviewAttr,
      reviewDefault: plugin.settings.reviewDefault,
      categoryAttr: plugin.settings.categoryAttr,
      categoryDefault: plugin.settings.categoryDefault
    }
  );
  const fileName = `${latest.basename}-\u6700\u65B0\u5185\u5BB9-${now.valueOf()}.md`;
  const outPath = joinOutputPath(plugin.settings.outputFolder, fileName);
  await ensureFolderExists(plugin.app, plugin.settings.outputFolder);
  await plugin.app.vault.create(outPath, `---
${frontmatter}
---
${last100}`);
  new import_obsidian2.Notice(`\u5DF2\u8F93\u51FA\uFF1A${outPath}`);
  return outPath;
}
function mapHttpError(status) {
  if (status === 401 || status === 403) return "API Key \u65E0\u6548";
  if (status === 402) return "\u4F59\u989D\u4E0D\u8DB3";
  if (status === 429) return "\u9650\u6D41";
  return "\u8BF7\u6C42\u5931\u8D25";
}
async function fetchModelList(apiKey, baseUrl) {
  var _a;
  const key = (apiKey || "").trim();
  if (!key) {
    const message = "\u8BF7\u5148\u586B\u5199 API Key";
    new import_obsidian2.Notice(message);
    return { ok: false, modelIds: [], message };
  }
  const base = (baseUrl || "https://api.deepseek.com").trim().replace(/\/+$/, "");
  try {
    const res = await (0, import_obsidian2.requestUrl)({
      url: `${base}/models`,
      method: "GET",
      headers: { Authorization: `Bearer ${key}` },
      throw: false
    });
    const body = typeof res.json === "function" ? await res.json() : res.json;
    if (res.status >= 200 && res.status < 300) {
      const data = body == null ? void 0 : body.data;
      const modelIds = Array.isArray(data) ? data.map((m) => m && typeof m.id === "string" ? m.id : "").filter((x) => x.length > 0) : [];
      const message2 = modelIds.length > 0 ? `\u6210\u529F\u83B7\u53D6 ${modelIds.length} \u4E2A\u6A21\u578B\uFF1A${modelIds[0]}` : "\u672A\u8FD4\u56DE\u4EFB\u4F55\u6A21\u578B";
      new import_obsidian2.Notice(message2);
      return { ok: true, modelIds, message: message2 };
    }
    const detail = bodySnippet(body);
    const message = detail ? `${mapHttpError(res.status)}\uFF08HTTP ${res.status}\uFF09\uFF1A${detail}` : `${mapHttpError(res.status)}\uFF08HTTP ${res.status}\uFF09`;
    new import_obsidian2.Notice(message);
    return { ok: false, modelIds: [], message };
  } catch (e) {
    const message = "\u7F51\u7EDC\u9519\u8BEF\uFF1A" + ((_a = e == null ? void 0 : e.message) != null ? _a : "\u672A\u77E5\u9519\u8BEF");
    new import_obsidian2.Notice(message);
    return { ok: false, modelIds: [], message };
  }
}

// src/settingsTab.ts
function renderSettings(app, plugin, containerEl) {
  new SettingsRenderer(app, plugin).render(containerEl);
}
var SettingsRenderer = class {
  constructor(app, plugin) {
    this.activeTab = "connection";
    this.modelDropdown = null;
    this.groupEls = [];
    this.groupCollapsed = /* @__PURE__ */ new Map();
    this.app = app;
    this.plugin = plugin;
    this.currentModels = Array.isArray(plugin.settings.models) ? plugin.settings.models.slice() : [];
  }
  render(containerEl) {
    this.containerEl = containerEl;
    containerEl.empty();
    this.modelDropdown = null;
    this.groupEls = [];
    this.groupCollapsed.clear();
    this.renderTabs(containerEl);
    this.renderSearch(containerEl);
    this.renderActiveTab(containerEl.createDiv({ cls: "ks-tab-content" }));
  }
  // -------------------------------------------------------------------------
  // tab bar / search / active tab
  // -------------------------------------------------------------------------
  renderTabs(containerEl) {
    const tabs = [
      { id: "connection", label: "\u8FDE\u63A5" },
      { id: "folder", label: "\u6587\u4EF6\u5939" },
      { id: "time", label: "\u65F6\u95F4" },
      { id: "output", label: "\u8F93\u51FA\u5C5E\u6027" },
      { id: "test", label: "\u6D4B\u8BD5\u5DE5\u5177" }
    ];
    const tabsEl = containerEl.createDiv({ cls: "ks-tabs" });
    for (const tab of tabs) {
      const tabEl = tabsEl.createDiv({ cls: "ks-tab" });
      tabEl.setText(tab.label);
      tabEl.dataset.tabId = tab.id;
      if (this.activeTab === tab.id) tabEl.addClass("is-active");
      tabEl.addEventListener("click", () => {
        this.activeTab = tab.id;
        this.render(this.containerEl);
      });
    }
  }
  renderActiveTab(containerEl) {
    switch (this.activeTab) {
      case "connection":
        this.renderConnectionGroup(containerEl);
        this.renderCustomProviderGroup(containerEl);
        break;
      case "folder":
        this.renderFolderGroup(containerEl);
        break;
      case "time":
        this.renderTimeGroup(containerEl);
        break;
      case "output":
        this.renderOutputGroup(containerEl);
        break;
      case "test":
        this.renderTestGroup(containerEl);
        break;
    }
  }
  renderSearch(containerEl) {
    const wrap = containerEl.createDiv({ cls: "ks-search" });
    const iconEl = wrap.createSpan({ cls: "ks-search-icon" });
    (0, import_obsidian3.setIcon)(iconEl, "search");
    const input = wrap.createEl("input", { cls: "ks-search-input" });
    input.type = "text";
    input.placeholder = "\u641C\u7D22\u8BBE\u7F6E...";
    input.addEventListener("input", () => this.filterSettings(input.value));
  }
  createGroup(containerEl, title, collapsed) {
    const groupEl = containerEl.createDiv({ cls: "ks-group" });
    const headingEl = groupEl.createDiv({ cls: "ks-group-heading" });
    const iconEl = headingEl.createSpan({ cls: "ks-group-icon" });
    (0, import_obsidian3.setIcon)(iconEl, collapsed ? "chevron-right" : "chevron-down");
    headingEl.createSpan({ cls: "ks-group-title", text: title });
    const bodyEl = groupEl.createDiv({ cls: "ks-group-body" });
    if (collapsed) groupEl.addClass("ks-collapsed");
    this.groupCollapsed.set(groupEl, collapsed);
    this.groupEls.push(groupEl);
    headingEl.addEventListener("click", () => {
      const isCollapsed = groupEl.hasClass("ks-collapsed");
      groupEl.toggleClass("ks-collapsed", !isCollapsed);
      this.groupCollapsed.set(groupEl, !isCollapsed);
      (0, import_obsidian3.setIcon)(iconEl, isCollapsed ? "chevron-down" : "chevron-right");
    });
    return bodyEl;
  }
  markSearchable(setting, text) {
    setting.settingEl.setAttribute("data-search", text);
  }
  updateSetting(key, value) {
    this.plugin.settings[key] = value;
    void this.plugin.saveSettings();
  }
  filterSettings(query) {
    const q = (query || "").trim().toLowerCase();
    const content = this.containerEl.querySelector(".ks-tab-content");
    if (!content) return;
    content.querySelectorAll(".setting-item").forEach((el) => {
      const elm = el;
      const hay = ((elm.getAttribute("data-search") || "") + " " + (elm.textContent || "")).toLowerCase();
      elm.style.display = q && hay.includes(q) ? "" : q ? "none" : "";
    });
    for (const groupEl of this.groupEls) {
      if (q) {
        groupEl.removeClass("ks-collapsed");
      } else if (this.groupCollapsed.get(groupEl)) {
        groupEl.addClass("ks-collapsed");
      } else {
        groupEl.removeClass("ks-collapsed");
      }
    }
  }
  // -------------------------------------------------------------------------
  // connection
  // -------------------------------------------------------------------------
  renderConnectionGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u8FDE\u63A5", false);
    const apiKey = new import_obsidian3.Setting(bodyEl).setName("API Key").setDesc("DeepSeek \u6216\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684 API Key\uFF0C\u7528\u4E8E\u83B7\u53D6\u6A21\u578B\u5217\u8868\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u7C98\u8D34\u4F60\u7684 API Key").setValue(this.plugin.settings.apiKey).onChange((value) => this.updateSetting("apiKey", value));
    });
    this.markSearchable(apiKey, "\u8FDE\u63A5 api key API Key \u5BC6\u94A5");
    const test = new import_obsidian3.Setting(bodyEl).setName("\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B").setDesc("\u8C03\u7528\u670D\u52A1\u5546 GET /models \u63A5\u53E3\uFF0C\u5E76\u586B\u5145\u4E0B\u65B9\u6A21\u578B\u4E0B\u62C9\u6846\u3002").addButton(
      (btn) => btn.setButtonText("\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B").setCta().onClick(async () => {
        await this.refreshModels();
      })
    );
    this.markSearchable(test, "\u8FDE\u63A5 \u6D4B\u8BD5 \u83B7\u53D6 \u6A21\u578B \u5237\u65B0");
    const model = new import_obsidian3.Setting(bodyEl).setName("\u9ED8\u8BA4\u6A21\u578B").setDesc("\u53EF\u7528\u7684\u6A21\u578B\u5217\u8868\uFF08\u6765\u81EA\u670D\u52A1\u5546 /models \u63A5\u53E3\uFF09\u3002").addDropdown((drop) => {
      this.modelDropdown = drop;
      this.populateModelDropdown(drop);
      drop.onChange((value) => this.updateSetting("model", value));
    });
    this.markSearchable(model, "\u8FDE\u63A5 \u9ED8\u8BA4\u6A21\u578B \u4E0B\u62C9 \u6A21\u578B");
  }
  renderCustomProviderGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546", true);
    const baseUrl = new import_obsidian3.Setting(bodyEl).setName("Base URL").setDesc("OpenAI \u517C\u5BB9\u670D\u52A1\u7684\u57FA\u7840\u5730\u5740\uFF0C\u9ED8\u8BA4 DeepSeek\u3002").addText(
      (text) => text.setPlaceholder("https://api.deepseek.com").setValue(this.plugin.settings.baseUrl).onChange((value) => this.updateSetting("baseUrl", value))
    );
    this.markSearchable(baseUrl, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 base_url \u5730\u5740 base url");
    const customApiKey = new import_obsidian3.Setting(bodyEl).setName("API Key").setDesc("\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684 API Key\uFF08\u9884\u7559\uFF09\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u7C98\u8D34\u4F60\u7684 API Key").setValue(this.plugin.settings.customApiKey).onChange((value) => this.updateSetting("customApiKey", value));
    });
    this.markSearchable(customApiKey, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 api_key \u5BC6\u94A5");
    const customModel = new import_obsidian3.Setting(bodyEl).setName("\u6A21\u578B").setDesc("\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684\u6A21\u578B ID\uFF08\u9884\u7559\uFF09\u3002").addText(
      (text) => text.setPlaceholder("model-id").setValue(this.plugin.settings.customModel).onChange((value) => this.updateSetting("customModel", value))
    );
    this.markSearchable(customModel, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 model \u6A21\u578B");
  }
  // -------------------------------------------------------------------------
  // folder
  // -------------------------------------------------------------------------
  renderFolderGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u6587\u4EF6\u5939", false);
    const source = new import_obsidian3.Setting(bodyEl).setName("\u6E90\u6587\u4EF6\u5939").setDesc("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570\u65F6\u626B\u63CF\u7684\u6587\u4EF6\u5939\u3002").addText((text) => {
      text.setPlaceholder("/").setValue(this.plugin.settings.sourceFolder).onChange((value) => this.updateSetting("sourceFolder", value));
      new FolderSuggest(this.app, text.inputEl);
    });
    this.markSearchable(source, "\u6587\u4EF6\u5939 \u6E90\u6587\u4EF6\u5939 \u8F93\u5165 \u76EE\u5F55");
    const output = new import_obsidian3.Setting(bodyEl).setName("\u8F93\u51FA\u6587\u4EF6\u5939").setDesc("\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5\u751F\u6210\u6587\u4EF6\u7684\u6587\u4EF6\u5939\u3002").addText((text) => {
      text.setPlaceholder("/").setValue(this.plugin.settings.outputFolder).onChange((value) => this.updateSetting("outputFolder", value));
      new FolderSuggest(this.app, text.inputEl);
    });
    this.markSearchable(output, "\u6587\u4EF6\u5939 \u8F93\u51FA\u6587\u4EF6\u5939 \u8F93\u5165 \u76EE\u5F55");
  }
  // -------------------------------------------------------------------------
  // time
  // -------------------------------------------------------------------------
  renderTimeGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u65F6\u95F4", false);
    const timeProp = new import_obsidian3.Setting(bodyEl).setName("\u65F6\u95F4\u5C5E\u6027\u540D").setDesc("\u8BFB\u53D6\u6587\u4EF6\u65F6\u95F4\u4F7F\u7528\u7684 frontmatter \u5C5E\u6027\u540D\uFF1B\u7559\u7A7A\u5219\u4F7F\u7528\u6587\u4EF6\u521B\u5EFA\u65F6\u95F4\u3002").addText(
      (text) => text.setPlaceholder("\u5982\uFF1Adate").setValue(this.plugin.settings.timeAttr).onChange((value) => this.updateSetting("timeAttr", value))
    );
    this.markSearchable(timeProp, "\u65F6\u95F4 \u65F6\u95F4\u5C5E\u6027\u540D \u5C5E\u6027 \u5B57\u6BB5");
    const timeFormat = new import_obsidian3.Setting(bodyEl).setName("\u65F6\u95F4\u6233\u683C\u5F0F").setDesc("moment \u517C\u5BB9\u7684\u65F6\u95F4\u683C\u5F0F\uFF0C\u4F8B\u5982 YYYY-MM-DD\u3002").addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.timeFormat).onChange((value) => this.updateSetting("timeFormat", value))
    );
    this.markSearchable(timeFormat, "\u65F6\u95F4 \u65F6\u95F4\u6233\u683C\u5F0F \u65F6\u95F4\u683C\u5F0F");
    const recentDays = new import_obsidian3.Setting(bodyEl).setName("\u6700\u8FD1 N \u5929").setDesc("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570\u65F6\u56DE\u770B\u7684\u5929\u6570\u3002").addText((text) => {
      text.inputEl.type = "number";
      text.setPlaceholder("7").setValue(String(this.plugin.settings.recentDays)).onChange((value) => {
        const n = parseInt(value, 10);
        if (!Number.isNaN(n) && n > 0) this.updateSetting("recentDays", n);
      });
    });
    this.markSearchable(recentDays, "\u65F6\u95F4 \u6700\u8FD1N\u5929 \u5929\u6570 \u6700\u8FD1");
  }
  // -------------------------------------------------------------------------
  // output (fixed timestamp/source rows + dynamic key→default-value rows)
  // -------------------------------------------------------------------------
  renderOutputGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u8F93\u51FA\u5C5E\u6027", false);
    const timestampProp = new import_obsidian3.Setting(bodyEl).setName("\u65F6\u95F4\u6233\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u5F53\u524D\u65F6\u95F4\u6233\u5C5E\u6027\u540D\uFF1B\u503C\u6309\u300C\u65F6\u95F4\u300D\u9875\u7684\u65F6\u95F4\u6233\u683C\u5F0F\u751F\u6210\u3002").addText(
      (text) => text.setPlaceholder("created").setValue(this.plugin.settings.timestampProperty).onChange((value) => this.updateSetting("timestampProperty", value))
    );
    this.markSearchable(timestampProp, "\u8F93\u51FA\u5C5E\u6027 \u65F6\u95F4\u6233\u5C5E\u6027\u540D created \u65F6\u95F4\u6233");
    const sourceAttr = new import_obsidian3.Setting(bodyEl).setName("\u6765\u6E90\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u6765\u6E90\u8DEF\u5F84\u5C5E\u6027\u540D\u3002").addText(
      (text) => text.setPlaceholder("source").setValue(this.plugin.settings.sourceAttr).onChange((value) => this.updateSetting("sourceAttr", value))
    );
    this.markSearchable(sourceAttr, "\u8F93\u51FA\u5C5E\u6027 \u6765\u6E90\u5C5E\u6027\u540D source \u6765\u6E90");
    const extraEl = bodyEl.createDiv({ cls: "ks-extra-props" });
    this.renderExtraProperties(extraEl);
    const addBtn = new import_obsidian3.Setting(bodyEl).setName("").setDesc("").addButton(
      (btn) => btn.setButtonText("+ \u6DFB\u52A0\u5C5E\u6027").onClick(() => {
        this.plugin.settings.extraProperties.push({ key: "", value: "" });
        void this.plugin.saveSettings();
        this.renderExtraProperties(extraEl);
      })
    );
    this.markSearchable(addBtn, "\u8F93\u51FA\u5C5E\u6027 \u6DFB\u52A0\u5C5E\u6027 \u589E\u52A0 \u6DFB\u52A0");
  }
  /** Render each extra property as a row: key input, value input, delete button. */
  renderExtraProperties(containerEl) {
    containerEl.empty();
    const list = this.plugin.settings.extraProperties || [];
    list.forEach((entry, index) => {
      const row = new import_obsidian3.Setting(containerEl).setName("").setDesc("").addText(
        (text) => text.setPlaceholder("\u5C5E\u6027\u540D").setValue(entry.key).onChange((value) => {
          entry.key = value;
          void this.plugin.saveSettings();
        })
      ).addText(
        (text) => text.setPlaceholder("\u9ED8\u8BA4\u503C").setValue(entry.value).onChange((value) => {
          entry.value = value;
          void this.plugin.saveSettings();
        })
      ).addButton(
        (btn) => btn.setIcon("trash-2").setTooltip("\u5220\u9664").onClick(() => {
          const a = this.plugin.settings.extraProperties;
          a.splice(index, 1);
          void this.plugin.saveSettings();
          this.renderExtraProperties(containerEl);
        })
      );
      row.settingEl.addClass("ks-extra-props-row");
      this.markSearchable(row, `\u8F93\u51FA\u5C5E\u6027 ${entry.key} ${entry.value}`);
    });
  }
  // -------------------------------------------------------------------------
  // test tools (execute the two commands without the command palette)
  // -------------------------------------------------------------------------
  renderTestGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u6D4B\u8BD5\u5DE5\u5177", false);
    const count = new import_obsidian3.Setting(bodyEl).setName("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570").setDesc("\u626B\u63CF\u6E90\u6587\u4EF6\u5939\uFF0C\u7EDF\u8BA1\u6700\u8FD1 N \u5929\u5185\u7684 Markdown \u6587\u4EF6\u6570\u3002").addButton(
      (btn) => btn.setButtonText("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570").setCta().onClick(() => {
        const n = countRecentFiles(this.plugin);
        new import_obsidian3.Notice(`\u6E90\u6587\u4EF6\u5939\u6700\u8FD1 ${this.plugin.settings.recentDays} \u5929\u5171\u6709 ${n} \u4E2A\u6587\u4EF6`);
      })
    );
    this.markSearchable(count, "\u6D4B\u8BD5 \u7EDF\u8BA1 \u6700\u8FD1\u6587\u4EF6\u6570 \u7EDF\u8BA1\u6700\u8FD1 \u7EDF\u8BA1");
    const output = new import_obsidian3.Setting(bodyEl).setName("\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5").setDesc("\u53D6\u6E90\u6587\u4EF6\u5939\u65F6\u95F4\u6700\u65B0\u7684\u6587\u4EF6\uFF0C\u5C06\u5176\u6B63\u6587\u6700\u540E 100 \u5B57\u7B26\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u5939\u3002").addButton(
      (btn) => btn.setButtonText("\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5").setCta().onClick(async () => {
        await outputLatestContent(this.plugin);
      })
    );
    this.markSearchable(output, "\u6D4B\u8BD5 \u8F93\u51FA \u6700\u65B0\u5185\u5BB9 \u8F93\u51FA\u6700\u65B0\u5185\u5BB9 \u8F93\u51FA");
  }
  // -------------------------------------------------------------------------
  // model fetching
  // -------------------------------------------------------------------------
  populateModelDropdown(drop) {
    drop.selectEl.empty();
    if (this.currentModels.length === 0) {
      drop.addOption("", "\uFF08\u8BF7\u5148\u70B9\u51FB\u201C\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B\u201D\uFF09");
      drop.setValue("");
      drop.setDisabled(true);
      return;
    }
    drop.setDisabled(false);
    const options = {};
    for (const model of this.currentModels) options[model] = model;
    drop.addOptions(options);
    const keep = this.plugin.settings.model;
    const value = this.currentModels.includes(keep) ? keep : this.currentModels[0];
    drop.setValue(value);
    this.updateSetting("model", value);
  }
  async refreshModels() {
    const result = await this.plugin.fetchModels(
      this.plugin.settings.apiKey,
      this.plugin.settings.baseUrl
    );
    if (result.ok) {
      this.currentModels = result.modelIds;
      if (this.modelDropdown) this.populateModelDropdown(this.modelDropdown);
    }
  }
};
var KnowledgeSystemSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    renderSettings(this.app, this.plugin, this.containerEl);
  }
};

// src/settingsView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_KS = "knowledge-system-settings-view";
var KnowledgeSettingsView = class extends import_obsidian4.ItemView {
  constructor(plugin, leaf) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_KS;
  }
  getIcon() {
    return "gear";
  }
  getDisplayText() {
    return "Knowledge System";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("ks-view");
    renderSettings(this.app, this.plugin, container);
  }
  async onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var KnowledgeSystemPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new KnowledgeSystemSettingTab(this.app, this));
    this.registerView(VIEW_TYPE_KS, (leaf) => new KnowledgeSettingsView(this, leaf));
    this.addCommand({
      id: "show-knowledge-system-settings-view",
      name: "Show Knowledge System settings view",
      callback: () => {
        void this.activateView();
      }
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_KS);
  }
  /** Open the standalone settings view in a new tab leaf. */
  async activateView() {
    if (typeof this.app.workspace.detachLeavesOfType === "function") {
      this.app.workspace.detachLeavesOfType(VIEW_TYPE_KS);
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_KS, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    this.migrateLegacyOutputProps();
  }
  /**
   * Move the legacy `reviewAttr`/`categoryAttr` output attributes into the new
   * `extraProperties` list the first time the plugin loads (only when the
   * dynamic list is empty). The old fields are kept for read compat.
   */
  migrateLegacyOutputProps() {
    this.settings.extraProperties = migrateExtraProperties(this.settings);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Fetch the provider's model list (GET /models). Exposed publicly so the
   * settings tab button and the harness both call it. On success the returned
   * ids are persisted onto the settings.
   */
  async fetchModels(apiKey, baseUrl) {
    const result = await fetchModelList(
      apiKey || this.settings.apiKey,
      baseUrl || this.settings.baseUrl
    );
    if (result.ok) {
      this.settings.models = result.modelIds;
      if (result.modelIds.length > 0) this.settings.model = result.modelIds[0];
      await this.saveSettings();
    }
    return result;
  }
};
