/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KnowledgeSystemPlugin2
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  baseUrl: "https://api.deepseek.com",
  model: "",
  models: [],
  sourceFolder: "/",
  outputFolder: "/",
  timeAttr: "",
  timeFormat: "YYYY-MM-DD",
  recentDays: 7,
  reviewAttr: "approved",
  reviewDefault: "\u672A\u5BA1",
  categoryAttr: "category",
  categoryDefault: "\u672A\u5206\u7C7B",
  timestampAttr: "created",
  sourceAttr: "source",
  customApiKey: "",
  customModel: ""
};

// src/commands.ts
var import_obsidian2 = require("obsidian");

// src/core.ts
var import_obsidian = require("obsidian");

// src/utils/index.ts
var DAY_MS = 864e5;
function parseTimestamp(value, moment, formats) {
  if (typeof value === "number") return value > 1e12 ? value : value * 1e3;
  if (value instanceof Date) return value.getTime();
  if (typeof value !== "string") return null;
  const s = value.trim();
  if (!s) return null;
  for (const f of formats) {
    if (!f) continue;
    const m = moment(s, f, true);
    if (m && typeof m.isValid === "function" && m.isValid()) return m.valueOf();
  }
  return null;
}
function resolveTimestamp(frontmatter, ctimeMs, moment, timeAttr, formats) {
  if (timeAttr) {
    const v = frontmatter[timeAttr];
    if (v !== void 0 && v !== null) {
      const ts = parseTimestamp(v, moment, formats);
      if (ts !== null) return ts;
    }
  }
  return ctimeMs;
}
function countRecent(items, opts) {
  const { moment, timeAttr, formats, nowMs, days } = opts;
  const cutoff = nowMs - Math.max(1, Math.floor(days || 1)) * DAY_MS;
  let n = 0;
  for (const item of items) {
    if (!item.isMd) continue;
    const ts = resolveTimestamp(item.frontmatter, item.ctimeMs, moment, timeAttr, formats);
    if (ts >= cutoff) n++;
  }
  return n;
}
function extractLastChars(text, n) {
  return [...text].slice(-n).join("");
}
function buildFrontmatter(vals, cfg) {
  const timeStr = cfg.moment(vals.timestampMs).format(cfg.timeFormat);
  return [
    `${cfg.timestampAttr}: ${timeStr}`,
    `${cfg.reviewAttr}: ${cfg.reviewDefault}`,
    `${cfg.categoryAttr}: ${cfg.categoryDefault}`,
    `${cfg.sourceAttr}: ${vals.source}`
  ].join("\n");
}
function stripFrontmatter(content) {
  if (content.startsWith("---")) {
    const idx = content.indexOf("\n---", 3);
    if (idx >= 0) {
      let rest = content.slice(idx + 4);
      if (rest.startsWith("\n")) rest = rest.slice(1);
      return rest;
    }
  }
  return content;
}

// src/core.ts
var FALLBACK_FORMATS = ["YYYY-MM-DD", "YYYY.MM.DD", "YYYY/MM/DD"];
function formatsFor(plugin) {
  const f = (plugin.settings.timeFormat || "").trim();
  return [f, ...FALLBACK_FORMATS].filter((x, i, arr) => !!x && arr.indexOf(x) === i);
}
function frontmatterOf(app, file) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  return (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
}
function appRequestUrl(app, params) {
  return app.requestUrl(params);
}
function resolveSourceFolder(plugin) {
  const raw = (plugin.settings.sourceFolder || "/").trim();
  if (raw === "/" || raw === "") return vaultRoot(plugin.app);
  const p = raw.replace(/^\/+|\/+$/g, "");
  const found = plugin.app.vault.getAbstractFileByPath(p);
  return found instanceof import_obsidian.TFolder ? found : vaultRoot(plugin.app);
}
function vaultRoot(app) {
  var _a;
  const vault = app.vault;
  if (typeof vault.getRoot === "function") {
    const r = vault.getRoot();
    if (r instanceof import_obsidian.TFolder) return r;
  }
  const byEmpty = app.vault.getAbstractFileByPath("");
  return byEmpty instanceof import_obsidian.TFolder ? byEmpty : (_a = vault.getRoot) == null ? void 0 : _a.call(vault);
}
function getMarkdownFilesInFolder(folder) {
  const result = [];
  const visit = (f) => {
    for (const child of f.children) {
      if (child instanceof import_obsidian.TFile && child.extension === "md") {
        result.push(child);
      } else if (child instanceof import_obsidian.TFolder) {
        visit(child);
      }
    }
  };
  visit(folder);
  return result;
}
function countRecentFiles(plugin) {
  const folder = resolveSourceFolder(plugin);
  const files = getMarkdownFilesInFolder(folder);
  const items = files.map((file) => ({
    isMd: true,
    frontmatter: frontmatterOf(plugin.app, file),
    ctimeMs: file.stat.ctime
  }));
  return countRecent(items, {
    moment: window.moment,
    timeAttr: plugin.settings.timeAttr || "",
    formats: formatsFor(plugin),
    nowMs: Date.now(),
    days: plugin.settings.recentDays
  });
}
function joinOutputPath(folder, name) {
  const raw = (folder || "/").trim();
  const base = raw === "/" || raw === "" ? "" : raw.replace(/^\/+|\/+$/g, "");
  const joined = base ? `${base}/${name}` : name;
  return joined.replace(/\/+/g, "/").replace(/^\/+/, "");
}
async function ensureFolderExists(app, folder) {
  const raw = (folder || "/").trim();
  const parts = (raw === "/" || raw === "" ? "" : raw.replace(/^\/+|\/+$/g, "")).split("/").filter(Boolean);
  let cur = "";
  for (const part of parts) {
    cur = cur ? `${cur}/${part}` : part;
    if (!app.vault.getAbstractFileByPath(cur)) {
      await app.vault.createFolder(cur);
    }
  }
}
async function outputLatestContent(plugin) {
  const folder = resolveSourceFolder(plugin);
  const files = getMarkdownFilesInFolder(folder);
  if (files.length === 0) {
    new import_obsidian.Notice("\u6E90\u6587\u4EF6\u5939\u4E2D\u6CA1\u6709\u53EF\u7528\u7684 Markdown \u6587\u4EF6");
    return "";
  }
  const formats = formatsFor(plugin);
  const timeAttr = plugin.settings.timeAttr || "";
  const tsOf = (file) => resolveTimestamp(frontmatterOf(plugin.app, file), file.stat.ctime, window.moment, timeAttr, formats);
  let latest = files[0];
  let latestTs = tsOf(latest);
  for (const file of files) {
    const ts = tsOf(file);
    if (ts > latestTs) {
      latestTs = ts;
      latest = file;
    }
  }
  const raw = await plugin.app.vault.read(latest);
  const body = stripFrontmatter(raw);
  const last100 = extractLastChars(body, 100);
  const now = window.moment();
  const frontmatter = buildFrontmatter(
    { source: latest.path, timestampMs: now.valueOf() },
    {
      timestampAttr: plugin.settings.timestampAttr,
      reviewAttr: plugin.settings.reviewAttr,
      reviewDefault: plugin.settings.reviewDefault,
      categoryAttr: plugin.settings.categoryAttr,
      categoryDefault: plugin.settings.categoryDefault,
      sourceAttr: plugin.settings.sourceAttr,
      moment: window.moment,
      timeFormat: plugin.settings.timeFormat
    }
  );
  const fileName = `${latest.basename}-\u6700\u65B0\u5185\u5BB9-${now.valueOf()}.md`;
  const outPath = joinOutputPath(plugin.settings.outputFolder, fileName);
  await ensureFolderExists(plugin.app, plugin.settings.outputFolder);
  await plugin.app.vault.create(outPath, `---
${frontmatter}
---
${last100}`);
  new import_obsidian.Notice(`\u5DF2\u8F93\u51FA\uFF1A${outPath}`);
  return outPath;
}
function mapHttpError(status) {
  if (status === 401 || status === 403) return "API Key \u65E0\u6548";
  if (status === 402) return "\u4F59\u989D\u4E0D\u8DB3";
  if (status === 429) return "\u9650\u6D41";
  return `\u8BF7\u6C42\u5931\u8D25\uFF08HTTP ${status}\uFF09`;
}
async function fetchModelList(app, apiKey, baseUrl) {
  var _a;
  const key = (apiKey || "").trim();
  if (!key) {
    const message = "\u8BF7\u5148\u586B\u5199 API Key";
    new import_obsidian.Notice(message);
    return { ok: false, modelIds: [], message };
  }
  const base = (baseUrl || "https://api.deepseek.com").trim().replace(/\/+$/, "");
  try {
    const res = await appRequestUrl(app, {
      url: `${base}/models`,
      method: "GET",
      headers: { Authorization: `Bearer ${key}` },
      throw: false
    });
    const body = typeof res.json === "function" ? await res.json() : res.json;
    if (res.status >= 200 && res.status < 300) {
      const data = body == null ? void 0 : body.data;
      const modelIds = Array.isArray(data) ? data.map((m) => m && typeof m.id === "string" ? m.id : "").filter((x) => x.length > 0) : [];
      const message2 = modelIds.length > 0 ? `\u6210\u529F\u83B7\u53D6 ${modelIds.length} \u4E2A\u6A21\u578B` : "\u672A\u8FD4\u56DE\u4EFB\u4F55\u6A21\u578B";
      new import_obsidian.Notice(message2);
      return { ok: true, modelIds, message: message2 };
    }
    const message = mapHttpError(res.status);
    new import_obsidian.Notice(message);
    return { ok: false, modelIds: [], message };
  } catch (e) {
    const message = "\u7F51\u7EDC\u9519\u8BEF\uFF1A" + ((_a = e == null ? void 0 : e.message) != null ? _a : "\u672A\u77E5\u9519\u8BEF");
    new import_obsidian.Notice(message);
    return { ok: false, modelIds: [], message };
  }
}

// src/commands.ts
function registerCommands(plugin) {
  plugin.addCommand({
    id: "count-recent-files",
    name: "\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570",
    callback: () => {
      const count = countRecentFiles(plugin);
      new import_obsidian2.Notice(`\u6E90\u6587\u4EF6\u5939\u6700\u8FD1 ${plugin.settings.recentDays} \u5929\u5171\u6709 ${count} \u4E2A\u6587\u4EF6`);
    }
  });
  plugin.addCommand({
    id: "output-latest-content",
    name: "\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5",
    callback: async () => {
      await outputLatestContent(plugin);
    }
  });
}

// src/settingsTab.ts
var import_obsidian4 = require("obsidian");

// src/folderSuggest.ts
var import_obsidian3 = require("obsidian");
var FolderSuggest = class extends import_obsidian3.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const folders = [];
    const lower = (query || "").toLowerCase();
    const visit = (f) => {
      folders.push(f);
      f.children.forEach((c) => {
        if (c instanceof import_obsidian3.TFolder) visit(c);
      });
    };
    this.app.vault.getAllLoadedFiles().forEach((f) => {
      if (f instanceof import_obsidian3.TFolder) visit(f);
    });
    return folders.filter((f) => f.path.toLowerCase().includes(lower)).slice(0, 50);
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path || "/");
  }
  selectSuggestion(folder) {
    this.inputEl.value = folder.path || "/";
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/settingsTab.ts
var KnowledgeSystemSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.modelDropdown = null;
    this.currentModels = [];
    this.groupEls = [];
    this.groupCollapsed = /* @__PURE__ */ new Map();
    this.plugin = plugin;
  }
  // -------------------------------------------------------------------------
  // rendering
  // -------------------------------------------------------------------------
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.modelDropdown = null;
    this.currentModels = [];
    this.groupEls = [];
    this.groupCollapsed.clear();
    this.renderSearch(containerEl);
    this.renderConnectionGroup(containerEl);
    this.renderCustomProviderGroup(containerEl);
    this.renderFolderGroup(containerEl);
    this.renderTimeGroup(containerEl);
    this.renderOutputGroup(containerEl);
  }
  renderSearch(containerEl) {
    const wrap = containerEl.createDiv({ cls: "ks-search" });
    const iconEl = wrap.createSpan({ cls: "ks-search-icon" });
    (0, import_obsidian4.setIcon)(iconEl, "search");
    const input = wrap.createEl("input", { cls: "ks-search-input" });
    input.type = "text";
    input.placeholder = "\u641C\u7D22\u8BBE\u7F6E...";
    input.addEventListener("input", () => this.filterSettings(input.value));
  }
  createGroup(containerEl, title, collapsed) {
    const groupEl = containerEl.createDiv({ cls: "ks-group" });
    const headingEl = groupEl.createDiv({ cls: "ks-group-heading" });
    const iconEl = headingEl.createSpan({ cls: "ks-group-icon" });
    (0, import_obsidian4.setIcon)(iconEl, collapsed ? "chevron-right" : "chevron-down");
    headingEl.createSpan({ cls: "ks-group-title", text: title });
    const bodyEl = groupEl.createDiv({ cls: "ks-group-body" });
    if (collapsed) groupEl.addClass("ks-collapsed");
    this.groupCollapsed.set(groupEl, collapsed);
    this.groupEls.push(groupEl);
    headingEl.addEventListener("click", () => {
      const isCollapsed = groupEl.hasClass("ks-collapsed");
      groupEl.toggleClass("ks-collapsed", !isCollapsed);
      this.groupCollapsed.set(groupEl, !isCollapsed);
      (0, import_obsidian4.setIcon)(iconEl, isCollapsed ? "chevron-down" : "chevron-right");
    });
    return bodyEl;
  }
  markSearchable(setting, text) {
    setting.settingEl.setAttribute("data-search", text);
  }
  updateSetting(key, value) {
    this.plugin.settings[key] = value;
    void this.plugin.saveSettings();
  }
  // -------------------------------------------------------------------------
  // filter / collapse
  // -------------------------------------------------------------------------
  filterSettings(query) {
    const q = (query || "").trim().toLowerCase();
    const allItems = this.containerEl.querySelectorAll(".setting-item");
    allItems.forEach((el) => {
      const elm = el;
      const hay = ((elm.getAttribute("data-search") || "") + " " + (elm.textContent || "")).toLowerCase();
      elm.style.display = q && hay.includes(q) ? "" : q ? "none" : "";
    });
    for (const groupEl of this.groupEls) {
      if (q) {
        groupEl.removeClass("ks-collapsed");
      } else if (this.groupCollapsed.get(groupEl)) {
        groupEl.addClass("ks-collapsed");
      } else {
        groupEl.removeClass("ks-collapsed");
      }
    }
  }
  // -------------------------------------------------------------------------
  // groups
  // -------------------------------------------------------------------------
  renderConnectionGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u8FDE\u63A5", false);
    const apiKey = new import_obsidian4.Setting(bodyEl).setName("API Key").setDesc("DeepSeek \u6216\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684 API Key\uFF0C\u7528\u4E8E\u83B7\u53D6\u6A21\u578B\u5217\u8868\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u7C98\u8D34\u4F60\u7684 API Key").setValue(this.plugin.settings.apiKey).onChange((value) => this.updateSetting("apiKey", value));
    });
    this.markSearchable(apiKey, "\u8FDE\u63A5 api key API Key \u5BC6\u94A5");
    const test = new import_obsidian4.Setting(bodyEl).setName("\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B").setDesc("\u8C03\u7528\u670D\u52A1\u5546 GET /models \u63A5\u53E3\uFF0C\u5E76\u586B\u5145\u4E0B\u65B9\u6A21\u578B\u4E0B\u62C9\u6846\u3002").addButton(
      (btn) => btn.setButtonText("\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B").setCta().onClick(async () => {
        await this.refreshModels();
      })
    );
    this.markSearchable(test, "\u8FDE\u63A5 \u6D4B\u8BD5 \u83B7\u53D6 \u6A21\u578B \u5237\u65B0");
    const model = new import_obsidian4.Setting(bodyEl).setName("\u9ED8\u8BA4\u6A21\u578B").setDesc("\u53EF\u7528\u7684\u6A21\u578B\u5217\u8868\uFF08\u6765\u81EA\u670D\u52A1\u5546 /models \u63A5\u53E3\uFF09\u3002").addDropdown((drop) => {
      this.modelDropdown = drop;
      this.populateModelDropdown(drop);
      drop.onChange((value) => this.updateSetting("model", value));
    });
    this.markSearchable(model, "\u8FDE\u63A5 \u9ED8\u8BA4\u6A21\u578B \u4E0B\u62C9 \u6A21\u578B");
  }
  renderCustomProviderGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546", true);
    const baseUrl = new import_obsidian4.Setting(bodyEl).setName("Base URL").setDesc("OpenAI \u517C\u5BB9\u670D\u52A1\u7684\u57FA\u7840\u5730\u5740\uFF0C\u9ED8\u8BA4 DeepSeek\u3002").addText(
      (text) => text.setPlaceholder("https://api.deepseek.com").setValue(this.plugin.settings.baseUrl).onChange((value) => this.updateSetting("baseUrl", value))
    );
    this.markSearchable(baseUrl, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 base_url \u5730\u5740 base url");
    const customApiKey = new import_obsidian4.Setting(bodyEl).setName("API Key").setDesc("\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684 API Key\uFF08\u9884\u7559\uFF09\u3002").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("\u7C98\u8D34\u4F60\u7684 API Key").setValue(this.plugin.settings.customApiKey).onChange((value) => this.updateSetting("customApiKey", value));
    });
    this.markSearchable(customApiKey, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 api_key \u5BC6\u94A5");
    const customModel = new import_obsidian4.Setting(bodyEl).setName("\u6A21\u578B").setDesc("\u81EA\u5B9A\u4E49\u670D\u52A1\u5546\u7684\u6A21\u578B ID\uFF08\u9884\u7559\uFF09\u3002").addText(
      (text) => text.setPlaceholder("model-id").setValue(this.plugin.settings.customModel).onChange((value) => this.updateSetting("customModel", value))
    );
    this.markSearchable(customModel, "\u81EA\u5B9A\u4E49\u670D\u52A1\u5546 model \u6A21\u578B");
  }
  renderFolderGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u6587\u4EF6\u5939", false);
    const source = new import_obsidian4.Setting(bodyEl).setName("\u6E90\u6587\u4EF6\u5939").setDesc("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570\u65F6\u626B\u63CF\u7684\u6587\u4EF6\u5939\u3002").addText((text) => {
      text.setPlaceholder("/").setValue(this.plugin.settings.sourceFolder).onChange((value) => this.updateSetting("sourceFolder", value));
      new FolderSuggest(this.app, text.inputEl);
    });
    this.markSearchable(source, "\u6587\u4EF6\u5939 \u6E90\u6587\u4EF6\u5939 \u8F93\u5165 \u76EE\u5F55");
    const output = new import_obsidian4.Setting(bodyEl).setName("\u8F93\u51FA\u6587\u4EF6\u5939").setDesc("\u8F93\u51FA\u6700\u65B0\u5185\u5BB9\u6D4B\u8BD5\u751F\u6210\u6587\u4EF6\u7684\u6587\u4EF6\u5939\u3002").addText((text) => {
      text.setPlaceholder("/").setValue(this.plugin.settings.outputFolder).onChange((value) => this.updateSetting("outputFolder", value));
      new FolderSuggest(this.app, text.inputEl);
    });
    this.markSearchable(output, "\u6587\u4EF6\u5939 \u8F93\u51FA\u6587\u4EF6\u5939 \u8F93\u5165 \u76EE\u5F55");
  }
  renderTimeGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u65F6\u95F4", false);
    const timeProp = new import_obsidian4.Setting(bodyEl).setName("\u65F6\u95F4\u5C5E\u6027\u540D").setDesc("\u8BFB\u53D6\u6587\u4EF6\u65F6\u95F4\u4F7F\u7528\u7684 frontmatter \u5C5E\u6027\u540D\uFF1B\u7559\u7A7A\u5219\u4F7F\u7528\u6587\u4EF6\u521B\u5EFA\u65F6\u95F4\u3002").addText(
      (text) => text.setPlaceholder("\u5982\uFF1Adate").setValue(this.plugin.settings.timeAttr).onChange((value) => this.updateSetting("timeAttr", value))
    );
    this.markSearchable(timeProp, "\u65F6\u95F4 \u65F6\u95F4\u5C5E\u6027\u540D \u5C5E\u6027 \u5B57\u6BB5");
    const timeFormat = new import_obsidian4.Setting(bodyEl).setName("\u65F6\u95F4\u6233\u683C\u5F0F").setDesc("moment \u517C\u5BB9\u7684\u65F6\u95F4\u683C\u5F0F\uFF0C\u4F8B\u5982 YYYY-MM-DD\u3002").addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.timeFormat).onChange((value) => this.updateSetting("timeFormat", value))
    );
    this.markSearchable(timeFormat, "\u65F6\u95F4 \u65F6\u95F4\u6233\u683C\u5F0F \u65F6\u95F4\u683C\u5F0F");
    const recentDays = new import_obsidian4.Setting(bodyEl).setName("\u6700\u8FD1 N \u5929").setDesc("\u7EDF\u8BA1\u6700\u8FD1\u6587\u4EF6\u6570\u65F6\u56DE\u770B\u7684\u5929\u6570\u3002").addText((text) => {
      text.inputEl.type = "number";
      text.setPlaceholder("7").setValue(String(this.plugin.settings.recentDays)).onChange((value) => {
        const n = parseInt(value, 10);
        if (!Number.isNaN(n) && n > 0) this.updateSetting("recentDays", n);
      });
    });
    this.markSearchable(recentDays, "\u65F6\u95F4 \u6700\u8FD1N\u5929 \u5929\u6570 \u6700\u8FD1");
  }
  renderOutputGroup(containerEl) {
    const bodyEl = this.createGroup(containerEl, "\u8F93\u51FA\u5C5E\u6027", false);
    const reviewProp = new import_obsidian4.Setting(bodyEl).setName("\u5BA1\u6838\u72B6\u6001\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u5BA1\u6838\u72B6\u6001\u5C5E\u6027\u540D\u3002").addText(
      (text) => text.setPlaceholder("approved").setValue(this.plugin.settings.reviewAttr).onChange((value) => this.updateSetting("reviewAttr", value))
    );
    this.markSearchable(reviewProp, "\u8F93\u51FA\u5C5E\u6027 \u5BA1\u6838\u72B6\u6001\u5C5E\u6027\u540D \u72B6\u6001");
    const reviewVal = new import_obsidian4.Setting(bodyEl).setName("\u5BA1\u6838\u72B6\u6001\u9ED8\u8BA4\u503C").setDesc("\u5199\u5165\u5BA1\u6838\u72B6\u6001\u5C5E\u6027\u7684\u9ED8\u8BA4\u503C\u3002").addText(
      (text) => text.setValue(this.plugin.settings.reviewDefault).onChange((value) => this.updateSetting("reviewDefault", value))
    );
    this.markSearchable(reviewVal, "\u8F93\u51FA\u5C5E\u6027 \u5BA1\u6838\u72B6\u6001\u9ED8\u8BA4\u503C");
    const categoryProp = new import_obsidian4.Setting(bodyEl).setName("\u5206\u7C7B\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u5206\u7C7B\u5C5E\u6027\u540D\u3002").addText(
      (text) => text.setPlaceholder("category").setValue(this.plugin.settings.categoryAttr).onChange((value) => this.updateSetting("categoryAttr", value))
    );
    this.markSearchable(categoryProp, "\u8F93\u51FA\u5C5E\u6027 \u5206\u7C7B\u5C5E\u6027\u540D \u5206\u7C7B");
    const categoryVal = new import_obsidian4.Setting(bodyEl).setName("\u5206\u7C7B\u9ED8\u8BA4\u503C").setDesc("\u5199\u5165\u5206\u7C7B\u5C5E\u6027\u7684\u9ED8\u8BA4\u503C\u3002").addText(
      (text) => text.setValue(this.plugin.settings.categoryDefault).onChange((value) => this.updateSetting("categoryDefault", value))
    );
    this.markSearchable(categoryVal, "\u8F93\u51FA\u5C5E\u6027 \u5206\u7C7B\u9ED8\u8BA4\u503C");
    const timestampProp = new import_obsidian4.Setting(bodyEl).setName("\u65F6\u95F4\u6233\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u5F53\u524D\u65F6\u95F4\u6233\u5C5E\u6027\u540D\u3002").addText(
      (text) => text.setPlaceholder("created").setValue(this.plugin.settings.timestampAttr).onChange((value) => this.updateSetting("timestampAttr", value))
    );
    this.markSearchable(timestampProp, "\u8F93\u51FA\u5C5E\u6027 \u65F6\u95F4\u6233\u5C5E\u6027\u540D created");
    const sourceAttr = new import_obsidian4.Setting(bodyEl).setName("\u6765\u6E90\u5C5E\u6027\u540D").setDesc("\u5199\u5165\u8F93\u51FA\u6587\u4EF6\u7684\u6765\u6E90\u8DEF\u5F84\u5C5E\u6027\u540D\u3002").addText(
      (text) => text.setPlaceholder("source").setValue(this.plugin.settings.sourceAttr).onChange((value) => this.updateSetting("sourceAttr", value))
    );
    this.markSearchable(sourceAttr, "\u8F93\u51FA\u5C5E\u6027 \u6765\u6E90\u5C5E\u6027\u540D source");
  }
  // -------------------------------------------------------------------------
  // model fetching
  // -------------------------------------------------------------------------
  populateModelDropdown(drop) {
    drop.selectEl.empty();
    if (this.currentModels.length === 0) {
      drop.addOption("", "\uFF08\u8BF7\u5148\u70B9\u51FB\u201C\u6D4B\u8BD5\u5E76\u83B7\u53D6\u6A21\u578B\u201D\uFF09");
      drop.setValue("");
      drop.setDisabled(true);
      return;
    }
    drop.setDisabled(false);
    const options = {};
    for (const model of this.currentModels) options[model] = model;
    drop.addOptions(options);
    const keep = this.plugin.settings.model;
    const value = this.currentModels.includes(keep) ? keep : this.currentModels[0];
    drop.setValue(value);
    this.updateSetting("model", value);
  }
  async refreshModels() {
    const result = await this.plugin.fetchModels(
      this.plugin.settings.apiKey,
      this.plugin.settings.baseUrl
    );
    if (result.ok) {
      this.currentModels = result.modelIds;
      if (this.modelDropdown) this.populateModelDropdown(this.modelDropdown);
    }
  }
};

// src/main.ts
var KnowledgeSystemPlugin2 = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    registerCommands(this);
    this.addSettingTab(new KnowledgeSystemSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * Fetch the provider's model list (GET /models). Exposed as a public method
   * so the settings tab button and the acceptance harness both call it. On
   * success the returned ids are also persisted onto the settings.
   */
  async fetchModels(apiKey, baseUrl) {
    const result = await fetchModelList(
      this.app,
      apiKey || this.settings.apiKey,
      baseUrl || this.settings.baseUrl
    );
    if (result.ok) {
      this.settings.models = result.modelIds;
      if (result.modelIds.length > 0) this.settings.model = result.modelIds[0];
      await this.saveSettings();
    }
    return result;
  }
};
